const ZUZU_POLICY = {
  en: {
    dir: "ltr", back: "← BieMTech Privacy Policies", subtitle: "Privacy Policy", audience: "Recommended for ages 6+ · General-audience game", rights: "All rights reserved.", app: "Application", pkg: "Package", updated: "Last updated", date: "August 30, 2026",
    summary: "<strong>In short:</strong> Zuzu: Bloomflight keeps core game progress and preferences on your device and does not sell personal data. Core play works offline. Optional Google Play Games sign-in and leaderboards use Google's service only when you choose those features. The game contains no ads, analytics, or purchases.",
    futureAds: "<strong>Possible future change:</strong> Advertising is being considered for a future version. Advertising is not active in the current version. Before any ad-enabled release, this policy and the app-store declarations will be updated to name the provider(s), describe any data access, collection, or sharing, and explain required consent and child-safety controls.",
    sections: [
      ["1. About This App", "<p>Zuzu: Bloomflight is a one-touch arcade game in which players guide a friendly cartoon bee through six changing gardens, tap to fly, hold to hover, bloom flowers, manage nectar, collect power-ups, build combos, and chase a high score.</p><p>It is a general-audience game recommended for players <strong>aged 6 and up</strong>. It is not designed exclusively for children.</p>"],
      ["2. Personal Data and Google Play Games", "<p>Zuzu: Bloomflight itself does <strong>not ask for or collect</strong> your name, email address, phone number, location, contacts, photos, media, or payment information.</p><p>If you choose Google Play Games sign-in or the online leaderboard, Google may process your Play Games account, player identifier, profile, and score data under Google's own privacy policy. The game submits scores and reads leaderboard entries only for that optional feature.</p>"],
      ["3. Information Stored Only on Your Device", "<p>The game stores a small local configuration file containing:</p><ul><li>best score, games played, flowers bloomed, and furthest garden reached;</li><li>language, sound, music, optional vibration, and bright-mode preferences.</li></ul><p>On first launch, the device language may be read locally to choose a supported interface language. None of this information leaves the device or is available to BieMTech.</p>"],
      ["4. Offline Use, Connectivity, and Permissions", "<p>Core gameplay works offline. Internet access is used only for optional Google Play Games sign-in and leaderboards. The game may use vibration for optional haptic feedback and does not request location, camera, microphone, contacts, photos, external storage, notifications, or other sensitive permissions.</p>"],
      ["5. Children and Age Guidance", "<p>The game has no registration, chat, social profile, user-generated content, advertising, gambling, or purchases. Its content consists of a friendly cartoon bee, flowers, fantasy garden obstacles, and a brief non-graphic collision when a run ends. There is no blood, gore, realistic violence, or frightening content.</p><p>Because success requires timing, resource management, and quick reactions, BieMTech recommends <strong>ages 6 and up</strong> while considering the game suitable for a broad audience. Official store ratings are assigned separately by regional rating authorities.</p>"],
      ["6. Advertising, Analytics, and Third Parties", "<p>The current version contains no ads and no third-party analytics, tracking, crash-reporting, cloud-save, social-network, or purchase SDKs. Google Play Games is the only optional online integration and is governed by Google's policies. Google Play may also process store and device data separately from the game.</p>"],
      ["7. Retention, Security, and Deletion", "<p>Local settings and game statistics remain on the device until you delete them. You can remove all local data by clearing the app's storage in Android Settings or uninstalling the app. Because no data is sent to a BieMTech server, no server-side deletion request is necessary.</p>"],
      ["8. Changes and Contact", "<p>We may update this policy if the app or its data practices change. A revised policy will be published before the relevant release.</p><p>Questions can be sent to BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  az: {
    dir: "ltr", back: "← BieMTech Məxfilik Siyasətləri", subtitle: "Məxfilik Siyasəti", audience: "6+ yaş üçün tövsiyə olunur · Ümumi auditoriya oyunu", rights: "Bütün hüquqlar qorunur.", app: "Tətbiq", pkg: "Paket", updated: "Son yenilənmə", date: "30 avqust 2026",
    summary: "<strong>Qısa olaraq:</strong> Zuzu: Bloomflight əsas oyun irəliləyişini və seçimləri cihazda saxlayır, şəxsi məlumat satmır. Əsas oyun oflayn işləyir. İstəyə bağlı Google Play Games girişi və lider cədvəli yalnız siz seçəndə Google xidmətindən istifadə edir. Reklam, analitika və alış yoxdur.",
    futureAds: "<strong>Gələcəkdə mümkün dəyişiklik:</strong> Gələcək versiyalardan birində reklam əlavə edilməsi nəzərdən keçirilir. Cari versiyada reklam aktiv deyil. Reklamlı versiya yayımlanmazdan əvvəl provayderlər, məlumatlara çıxış, toplama və ya paylaşma, tələb olunan razılıq və uşaq təhlükəsizliyi tədbirləri açıqlanmaqla bu siyasət və tətbiq mağazası bəyannamələri yenilənəcək.",
    sections: [
      ["1. Tətbiq haqqında", "<p>Zuzu: Bloomflight oyunçunun mehriban cizgi arısı Zuzunu dəyişən altı bağdan keçirdiyi bir toxunuşlu arkada oyunudur. Oyunçu uçmaq üçün toxunur, havada qalmaq üçün basıb saxlayır, çiçəkləri açır, nektarı idarə edir, gücləndiricilər toplayır, kombolar qurur və rekord qazanmağa çalışır.</p><p>Ümumi auditoriya üçün nəzərdə tutulub və <strong>6 yaşdan yuxarı</strong> oyunçulara tövsiyə olunur. Yalnız uşaqlar üçün hazırlanmayıb.</p>"],
      ["2. Şəxsi məlumatlar və Google Play Games", "<p>Zuzu: Bloomflight ad, e-poçt, telefon, məkan, kontaktlar, şəkillər, media və ya ödəniş məlumatını <strong>istəmir və toplamır</strong>.</p><p>Google Play Games girişini və ya onlayn lider cədvəlini seçsəniz, Google hesab, oyunçu identifikatoru, profil və xal məlumatını öz siyasətinə əsasən emal edə bilər. Oyun yalnız bu istəyə bağlı funksiya üçün xal göndərir və cədvəli oxuyur.</p>"],
      ["3. Yalnız cihazda saxlanılan məlumat", "<p>Oyun kiçik lokal konfiqurasiya faylında bunları saxlayır:</p><ul><li>ən yaxşı xal, oyun sayı, açılmış çiçəklər və çatılmış ən uzaq bağ;</li><li>dil, səs, musiqi, seçimli vibrasiya və parlaq rejim seçimləri.</li></ul><p>İlk açılışda dəstəklənən interfeys dilini seçmək üçün cihazın dili lokal olaraq oxuna bilər. Bu məlumatların heç biri cihazdan çıxmır və BieMTech üçün əlçatan deyil.</p>"],
      ["4. Oflayn istifadə, bağlantı və icazələr", "<p>Əsas oyun oflayn işləyir. İnternet yalnız istəyə bağlı Google Play Games girişi və lider cədvəli üçün istifadə olunur. Oyun toxunma reaksiyası üçün vibrasiyadan istifadə edə bilər; məkan, kamera, mikrofon, kontaktlar, şəkillər, xarici yaddaş, bildirişlər və digər həssas icazələr istəmir.</p>"],
      ["5. Uşaqlar və yaş tövsiyəsi", "<p>Oyunda qeydiyyat, çat, sosial profil, istifadəçi məzmunu, reklam, qumar və satınalma yoxdur. Məzmun mehriban cizgi arısı, çiçəklər, fantastik bağ maneələri və gediş bitəndə qısa, qeyri-qrafik toqquşmadan ibarətdir. Qan, real zorakılıq və qorxuducu məzmun yoxdur.</p><p>Uğur zamanlama, resurs idarəsi və sürətli reaksiya tələb etdiyinə görə BieMTech oyunu <strong>6 yaş və yuxarı</strong> üçün tövsiyə edir və geniş auditoriyaya uyğun sayır. Rəsmi mağaza reytinqi regional qurumlar tərəfindən ayrıca verilir.</p>"],
      ["6. Reklam, analitika və üçüncü tərəflər", "<p>Cari versiyada reklam və analitika, izləmə, xəta hesabatı, bulud yaddaşı, sosial şəbəkə və ya alış üçün üçüncü tərəf SDK-sı yoxdur. Google Play Games yeganə istəyə bağlı onlayn inteqrasiyadır və Google siyasətlərinə tabedir. Google Play mağaza və cihaz məlumatlarını ayrıca emal edə bilər.</p>"],
      ["7. Saxlama, təhlükəsizlik və silinmə", "<p>Lokal seçimlər və oyun statistikası siz silənədək cihazda qalır. Android Ayarlarında tətbiq yaddaşını təmizləməklə və ya tətbiqi silməklə bütün lokal məlumatları silə bilərsiniz. BieMTech serverinə məlumat göndərilmədiyi üçün server tərəfli silinmə sorğusu lazım deyil.</p>"],
      ["8. Dəyişikliklər və əlaqə", "<p>Tətbiq və ya məlumat təcrübəsi dəyişərsə, bu siyasəti yeniləyə bilərik. Yenilənmiş siyasət aidiyyəti versiyadan əvvəl yayımlanacaq.</p><p>Suallar üçün BieMTech ilə əlaqə saxlayın:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  es: {
    dir: "ltr", back: "← Políticas de privacidad de BieMTech", subtitle: "Política de privacidad", audience: "Recomendado para mayores de 6 años · Juego para público general", rights: "Todos los derechos reservados.", app: "Aplicación", pkg: "Paquete", updated: "Última actualización", date: "30 de agosto de 2026",
    summary: "<strong>En resumen:</strong> Zuzu: Bloomflight guarda el progreso y las preferencias principales en el dispositivo y no vende datos personales. El juego principal funciona sin conexión. El inicio de sesión y las clasificaciones opcionales de Google Play Games usan el servicio de Google solo cuando eliges esas funciones. No hay anuncios, analíticas ni compras.",
    futureAds: "<strong>Posible cambio futuro:</strong> Se está considerando añadir publicidad en una versión futura. No hay publicidad activa actualmente. Antes de una versión con anuncios se actualizarán esta política y las declaraciones de la tienda para identificar proveedores, describir el acceso, la recopilación o el intercambio de datos y explicar el consentimiento y las medidas de protección infantil.",
    sections: [
      ["1. Sobre la aplicación", "<p>Zuzu: Bloomflight es un juego arcade de un toque en el que guías a una abeja de dibujos animados por seis jardines, vuelas, flotas, haces florecer plantas, gestionas néctar, recoges potenciadores y buscas récords.</p><p>Es un juego para público general recomendado para <strong>mayores de 6 años</strong>, no diseñado exclusivamente para niños.</p>"],
      ["2. Datos personales y Google Play Games", "<p>Zuzu: Bloomflight <strong>no solicita ni recopila</strong> tu nombre, correo, teléfono, ubicación, contactos, fotos, archivos multimedia ni datos de pago.</p><p>Si eliges iniciar sesión en Google Play Games o usar la clasificación online, Google puede tratar tu cuenta, identificador de jugador, perfil y puntuación según su propia política. El juego solo envía puntuaciones y lee la clasificación para esa función opcional.</p>"],
      ["3. Información guardada solo en el dispositivo", "<p>El juego guarda localmente:</p><ul><li>récord, partidas jugadas, flores abiertas y jardín más lejano;</li><li>idioma, sonido, música, vibración opcional y modo brillante.</li></ul><p>Al abrirlo por primera vez puede leer localmente el idioma del dispositivo. Nada sale del dispositivo ni está disponible para BieMTech.</p>"],
      ["4. Uso sin conexión, conectividad y permisos", "<p>El juego principal funciona sin conexión. Internet se usa solo para el inicio de sesión y las clasificaciones opcionales de Google Play Games. El juego puede usar vibración para respuesta háptica y no solicita ubicación, cámara, micrófono, contactos, fotos, almacenamiento externo, notificaciones ni otros permisos sensibles.</p>"],
      ["5. Niños y orientación de edad", "<p>No hay registro, chat, perfil social, contenido de usuarios, publicidad, apuestas ni compras. Solo aparecen una abeja amistosa, flores, obstáculos de fantasía y una colisión breve y no gráfica al terminar. No hay sangre, violencia realista ni contenido aterrador.</p><p>Por el ritmo, la gestión de recursos y los reflejos necesarios, BieMTech recomienda <strong>6 años o más</strong> y lo considera apto para un público amplio. Las clasificaciones oficiales dependen de cada región.</p>"],
      ["6. Publicidad, analíticas y terceros", "<p>La versión actual no contiene anuncios ni SDK de terceros para analíticas, seguimiento, informes de fallos, guardado en la nube, redes sociales o compras. Google Play Games es la única integración online opcional y se rige por las políticas de Google. Google Play también puede tratar datos de la tienda y del dispositivo por separado.</p>"],
      ["7. Conservación, seguridad y eliminación", "<p>Los ajustes y estadísticas permanecen en el dispositivo hasta que los elimines. Puedes borrar todo limpiando el almacenamiento de la app en Android o desinstalándola. Como no se envían datos a servidores de BieMTech, no hace falta solicitar su eliminación.</p>"],
      ["8. Cambios y contacto", "<p>Podemos actualizar esta política si cambian la aplicación o sus prácticas. La versión revisada se publicará antes del cambio correspondiente.</p><p>Contacto:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  pt: {
    dir: "ltr", back: "← Políticas de Privacidade BieMTech", subtitle: "Política de Privacidade", audience: "Recomendado para maiores de 6 anos · Jogo para público geral", rights: "Todos os direitos reservados.", app: "Aplicativo", pkg: "Pacote", updated: "Última atualização", date: "30 de agosto de 2026",
    summary: "<strong>Em resumo:</strong> Zuzu: Bloomflight guarda o progresso e as preferências principais no dispositivo e não vende dados pessoais. O jogo principal funciona offline. O login e os placares opcionais do Google Play Games usam o serviço do Google apenas quando você escolhe esses recursos. Não há anúncios, análises ou compras.",
    futureAds: "<strong>Possível mudança futura:</strong> A inclusão de publicidade está sendo considerada para uma versão futura. Não há anúncios ativos na versão atual. Antes de qualquer versão com anúncios, esta política e as declarações da loja serão atualizadas com fornecedores, acesso, coleta ou compartilhamento de dados e medidas de consentimento e proteção infantil.",
    sections: [
      ["1. Sobre o aplicativo", "<p>Zuzu: Bloomflight é um jogo arcade de um toque no qual você guia uma abelha amigável por seis jardins, toca para voar, segura para pairar, abre flores, gerencia néctar, coleta poderes e busca recordes.</p><p>É um jogo para público geral recomendado para <strong>maiores de 6 anos</strong>, não feito exclusivamente para crianças.</p>"],
      ["2. Dados pessoais e Google Play Games", "<p>Zuzu: Bloomflight <strong>não solicita nem coleta</strong> nome, e-mail, telefone, localização, contatos, fotos, mídia ou dados de pagamento.</p><p>Se você optar pelo login ou placar do Google Play Games, o Google poderá processar conta, identificador de jogador, perfil e pontuação conforme sua própria política. O jogo envia pontuações e lê o placar apenas para esse recurso opcional.</p>"],
      ["3. Informações apenas no dispositivo", "<p>O jogo guarda localmente:</p><ul><li>recorde, partidas, flores abertas e jardim mais distante;</li><li>idioma, som, música, vibração opcional e modo brilhante.</li></ul><p>Na primeira abertura, o idioma do dispositivo pode ser lido localmente. Nada sai do aparelho nem fica disponível para a BieMTech.</p>"],
      ["4. Uso offline, conectividade e permissões", "<p>O jogo principal funciona offline. A Internet é usada somente para login e placares opcionais do Google Play Games. O jogo pode usar vibração para retorno tátil e não solicita localização, câmera, microfone, contatos, fotos, armazenamento externo, notificações ou outras permissões sensíveis.</p>"],
      ["5. Crianças e idade", "<p>Não há cadastro, chat, perfil social, conteúdo de usuários, anúncios, apostas ou compras. Há apenas uma abelha amigável, flores, obstáculos de fantasia e uma colisão breve e não gráfica ao fim da rodada, sem sangue, violência realista ou conteúdo assustador.</p><p>Por exigir ritmo, gestão de recursos e reação rápida, a BieMTech recomenda <strong>6 anos ou mais</strong> e considera o jogo adequado a um público amplo. As classificações oficiais são definidas regionalmente.</p>"],
      ["6. Publicidade, análises e terceiros", "<p>A versão atual não contém anúncios nem SDKs de terceiros para análises, rastreamento, relatórios de falhas, nuvem, redes sociais ou compras. Google Play Games é a única integração online opcional e segue as políticas do Google. O Google Play também pode tratar dados da loja e do dispositivo separadamente.</p>"],
      ["7. Retenção, segurança e exclusão", "<p>Configurações e estatísticas ficam no aparelho até serem apagadas. Você pode remover tudo limpando o armazenamento do app no Android ou desinstalando-o. Como não há envio a servidores da BieMTech, não é necessário pedido de exclusão no servidor.</p>"],
      ["8. Alterações e contato", "<p>Podemos atualizar esta política se o aplicativo ou suas práticas mudarem. A revisão será publicada antes da versão relacionada.</p><p>Contato:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  fr: {
    dir: "ltr", back: "← Politiques de confidentialité BieMTech", subtitle: "Politique de confidentialité", audience: "Recommandé dès 6 ans · Jeu grand public", rights: "Tous droits réservés.", app: "Application", pkg: "Paquet", updated: "Dernière mise à jour", date: "30 août 2026",
    summary: "<strong>En bref :</strong> Zuzu: Bloomflight conserve la progression et les préférences principales sur l'appareil et ne vend pas de données personnelles. Le jeu principal fonctionne hors ligne. La connexion et les classements facultatifs de Google Play Games utilisent le service de Google seulement si vous les choisissez. Il n'y a ni publicité, ni analyse, ni achat.",
    futureAds: "<strong>Évolution future possible :</strong> L'ajout de publicité est envisagé pour une future version. Aucune publicité n'est active actuellement. Avant toute version avec publicité, cette politique et les déclarations de la boutique seront mises à jour pour nommer les fournisseurs, décrire tout accès, collecte ou partage de données, ainsi que le consentement et les protections des enfants.",
    sections: [
      ["1. À propos de l'application", "<p>Zuzu: Bloomflight est un jeu d'arcade à une touche où vous guidez une abeille sympathique dans six jardins, volez, planez, faites éclore des fleurs, gérez le nectar, ramassez des bonus et visez un record.</p><p>Ce jeu grand public est recommandé aux personnes de <strong>6 ans et plus</strong> et n'est pas conçu exclusivement pour les enfants.</p>"],
      ["2. Données personnelles et Google Play Games", "<p>Zuzu: Bloomflight <strong>ne demande et ne collecte pas</strong> votre nom, e-mail, téléphone, position, contacts, photos, médias ou données de paiement.</p><p>Si vous choisissez la connexion ou le classement Google Play Games, Google peut traiter votre compte, identifiant joueur, profil et score selon sa propre politique. Le jeu envoie les scores et lit le classement uniquement pour cette fonction facultative.</p>"],
      ["3. Informations stockées uniquement sur l'appareil", "<p>Le jeu garde localement :</p><ul><li>record, parties, fleurs écloses et jardin le plus éloigné ;</li><li>langue, son, musique, vibration facultative et mode lumineux.</li></ul><p>Au premier lancement, la langue de l'appareil peut être lue localement. Rien ne quitte l'appareil et BieMTech n'y a pas accès.</p>"],
      ["4. Mode hors ligne, connexion et autorisations", "<p>Le jeu principal fonctionne hors ligne. Internet sert uniquement à la connexion et aux classements facultatifs de Google Play Games. Le jeu peut utiliser la vibration pour le retour haptique et ne demande ni position, caméra, microphone, contacts, photos, stockage externe, notifications ou autre autorisation sensible.</p>"],
      ["5. Enfants et âge", "<p>Aucune inscription, discussion, profil social, contenu utilisateur, publicité, jeu d'argent ou achat. Le contenu montre une abeille amicale, des fleurs, des obstacles fantastiques et une brève collision non graphique, sans sang, violence réaliste ni contenu effrayant.</p><p>Le rythme, la gestion des ressources et les réflexes conduisent BieMTech à recommander <strong>6 ans et plus</strong>, tout en jugeant le jeu adapté à un large public. Les classements officiels dépendent des régions.</p>"],
      ["6. Publicité, analyses et tiers", "<p>La version actuelle ne contient ni publicité ni SDK tiers d'analyse, suivi, rapport de panne, sauvegarde cloud, réseau social ou achat. Google Play Games est la seule intégration en ligne facultative et relève des politiques de Google. Google Play peut aussi traiter séparément les données de boutique et d'appareil.</p>"],
      ["7. Conservation, sécurité et suppression", "<p>Les réglages et statistiques restent sur l'appareil jusqu'à leur suppression. Effacez le stockage de l'application dans Android ou désinstallez-la pour tout supprimer. Aucune demande côté serveur n'est nécessaire, car rien n'est envoyé à BieMTech.</p>"],
      ["8. Modifications et contact", "<p>Nous pouvons mettre à jour cette politique si l'application ou ses pratiques changent. La révision sera publiée avant la version concernée.</p><p>Contact :</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  de: {
    dir: "ltr", back: "← BieMTech-Datenschutzerklärungen", subtitle: "Datenschutzerklärung", audience: "Empfohlen ab 6 Jahren · Spiel für allgemeines Publikum", rights: "Alle Rechte vorbehalten.", app: "Anwendung", pkg: "Paket", updated: "Zuletzt aktualisiert", date: "30. August 2026",
    summary: "<strong>Kurz gesagt:</strong> Zuzu: Bloomflight speichert den grundlegenden Spielfortschritt und Einstellungen auf dem Gerät und verkauft keine personenbezogenen Daten. Das Hauptspiel funktioniert offline. Die optionale Google-Play-Games-Anmeldung und Bestenliste nutzt Googles Dienst nur nach Ihrer Auswahl. Es gibt keine Werbung, Analysen oder Käufe.",
    futureAds: "<strong>Mögliche spätere Änderung:</strong> Werbung wird für eine zukünftige Version erwogen. In der aktuellen Version ist keine Werbung aktiv. Vor einer werbefinanzierten Version werden diese Richtlinie und die Store-Angaben aktualisiert: Anbieter, Datenzugriff, Erhebung oder Weitergabe sowie Einwilligungs- und Kinderschutzmaßnahmen werden offengelegt.",
    sections: [
      ["1. Über die App", "<p>Zuzu: Bloomflight ist ein Ein-Tasten-Arcade-Spiel, in dem eine freundliche Cartoon-Biene durch sechs Gärten fliegt, schwebt, Blumen öffnet, Nektar verwaltet, Power-ups sammelt und Rekorde jagt.</p><p>Es ist für allgemeines Publikum und wird ab <strong>6 Jahren</strong> empfohlen. Es richtet sich nicht ausschließlich an Kinder.</p>"],
      ["2. Personenbezogene Daten und Google Play Games", "<p>Zuzu: Bloomflight <strong>fragt Name, E-Mail, Telefon, Standort, Kontakte, Fotos, Medien oder Zahlungsdaten nicht ab und erhebt sie nicht</strong>.</p><p>Wenn Sie Google Play Games oder die Online-Bestenliste nutzen, kann Google Konto, Spieler-ID, Profil und Punktestand nach eigenen Richtlinien verarbeiten. Das Spiel sendet Punkte und liest Einträge nur für diese optionale Funktion.</p>"],
      ["3. Nur auf dem Gerät gespeicherte Informationen", "<p>Lokal gespeichert werden:</p><ul><li>Rekord, Spiele, geöffnete Blüten und weitester Garten;</li><li>Sprache, Ton, Musik, optionale Vibration und heller Modus.</li></ul><p>Beim ersten Start kann die Gerätesprache lokal gelesen werden. Nichts verlässt das Gerät oder ist für BieMTech zugänglich.</p>"],
      ["4. Offline-Nutzung, Verbindung und Berechtigungen", "<p>Das Hauptspiel funktioniert offline. Internet wird nur für die optionale Google-Play-Games-Anmeldung und Bestenliste genutzt. Vibration kann für haptisches Feedback verwendet werden; Standort, Kamera, Mikrofon, Kontakte, Fotos, externer Speicher, Benachrichtigungen und andere sensible Rechte werden nicht angefordert.</p>"],
      ["5. Kinder und Altersempfehlung", "<p>Es gibt keine Registrierung, Chats, sozialen Profile, Nutzerinhalte, Werbung, Glücksspiele oder Käufe. Zu sehen sind eine freundliche Biene, Blumen, Fantasiehindernisse und eine kurze, unblutige Kollision am Ende eines Laufs – ohne Blut, realistische Gewalt oder Schreckinhalte.</p><p>Wegen Timing, Ressourcenplanung und Reaktion empfiehlt BieMTech <strong>ab 6 Jahren</strong> und hält das Spiel für ein breites Publikum geeignet. Offizielle Altersfreigaben werden regional vergeben.</p>"],
      ["6. Werbung, Analysen und Dritte", "<p>Die aktuelle Version enthält keine Werbung und keine Drittanbieter-SDKs für Analyse, Tracking, Fehlerberichte, Cloud-Speicher, soziale Netzwerke oder Käufe. Google Play Games ist die einzige optionale Online-Integration und unterliegt Googles Richtlinien. Google Play kann Store- und Gerätedaten separat verarbeiten.</p>"],
      ["7. Aufbewahrung, Sicherheit und Löschung", "<p>Einstellungen und Statistiken bleiben bis zur Löschung auf dem Gerät. Löschen Sie den App-Speicher in Android oder deinstallieren Sie die App. Da nichts an BieMTech-Server gesendet wird, ist keine serverseitige Anfrage nötig.</p>"],
      ["8. Änderungen und Kontakt", "<p>Wir können diese Richtlinie bei Änderungen an App oder Datenpraxis aktualisieren. Eine neue Fassung wird vor der betreffenden Version veröffentlicht.</p><p>Kontakt:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  ru: {
    dir: "ltr", back: "← Политики конфиденциальности BieMTech", subtitle: "Политика конфиденциальности", audience: "Рекомендуется с 6 лет · Игра для широкой аудитории", rights: "Все права защищены.", app: "Приложение", pkg: "Пакет", updated: "Последнее обновление", date: "30 августа 2026 г.",
    summary: "<strong>Кратко:</strong> Zuzu: Bloomflight хранит основной прогресс и настройки на устройстве и не продаёт персональные данные. Основная игра работает офлайн. Необязательные вход и рейтинг Google Play Games используют сервис Google только по вашему выбору. Рекламы, аналитики и покупок нет.",
    futureAds: "<strong>Возможное изменение:</strong> Реклама рассматривается для будущей версии. Сейчас она не активна. До выпуска версии с рекламой политика и декларации магазина будут обновлены: будут названы провайдеры, описаны доступ, сбор или передача данных, согласие и меры защиты детей.",
    sections: [
      ["1. О приложении", "<p>Zuzu: Bloomflight — аркада с управлением одним касанием: игрок ведёт дружелюбную мультяшную пчелу через шесть садов, летает, зависает, раскрывает цветы, управляет нектаром, собирает усиления и ставит рекорды.</p><p>Игра предназначена для широкой аудитории и рекомендуется <strong>с 6 лет</strong>. Она не создана исключительно для детей.</p>"],
      ["2. Персональные данные и Google Play Games", "<p>Zuzu: Bloomflight <strong>не запрашивает и не собирает</strong> имя, почту, телефон, местоположение, контакты, фотографии, медиа или платёжные данные.</p><p>Если вы выберете вход или онлайн-рейтинг Google Play Games, Google может обрабатывать аккаунт, идентификатор игрока, профиль и очки по своей политике. Игра отправляет очки и читает рейтинг только для этой необязательной функции.</p>"],
      ["3. Данные только на устройстве", "<p>Локально сохраняются:</p><ul><li>рекорд, число игр, распустившиеся цветы и самый дальний сад;</li><li>язык, звук, музыка, необязательная вибрация и яркий режим.</li></ul><p>При первом запуске язык устройства может быть прочитан локально. Данные не покидают устройство и недоступны BieMTech.</p>"],
      ["4. Офлайн-работа, подключение и разрешения", "<p>Основная игра работает офлайн. Интернет используется только для необязательных входа и рейтинга Google Play Games. Игра может использовать вибрацию и не запрашивает местоположение, камеру, микрофон, контакты, фотографии, внешнее хранилище, уведомления или другие чувствительные разрешения.</p>"],
      ["5. Дети и возраст", "<p>Нет регистрации, чата, социальных профилей, пользовательского контента, рекламы, азартных игр или покупок. Есть дружелюбная пчела, цветы, фантазийные препятствия и короткое неграфичное столкновение без крови, реалистичного насилия или пугающего контента.</p><p>Из-за требований к времени, ресурсам и реакции BieMTech рекомендует <strong>6+</strong>, считая игру подходящей широкой аудитории. Официальные рейтинги назначаются отдельно по регионам.</p>"],
      ["6. Реклама, аналитика и третьи стороны", "<p>В текущей версии нет рекламы и сторонних SDK для аналитики, отслеживания, отчётов об ошибках, облачных сохранений, соцсетей или покупок. Google Play Games — единственная необязательная онлайн-интеграция, регулируемая политиками Google. Google Play также может отдельно обрабатывать данные магазина и устройства.</p>"],
      ["7. Хранение, безопасность и удаление", "<p>Настройки и статистика остаются на устройстве до удаления. Очистите данные приложения в Android или удалите приложение. Так как данные не отправляются на сервер BieMTech, серверный запрос не нужен.</p>"],
      ["8. Изменения и контакты", "<p>Мы можем обновить политику при изменении приложения или работы с данными. Новая версия будет опубликована до соответствующего релиза.</p><p>Контакт:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  tr: {
    dir: "ltr", back: "← BieMTech Gizlilik Politikaları", subtitle: "Gizlilik Politikası", audience: "6+ yaş için önerilir · Genel izleyici oyunu", rights: "Tüm hakları saklıdır.", app: "Uygulama", pkg: "Paket", updated: "Son güncelleme", date: "30 Ağustos 2026",
    summary: "<strong>Kısaca:</strong> Zuzu: Bloomflight temel oyun ilerlemesini ve tercihleri cihazda tutar, kişisel veri satmaz. Ana oyun çevrimdışı çalışır. İsteğe bağlı Google Play Games girişi ve liderlik tablosu yalnızca seçtiğinizde Google hizmetini kullanır. Reklam, analiz veya satın alma yoktur.",
    futureAds: "<strong>Gelecekte olası değişiklik:</strong> İlerideki bir sürüm için reklam değerlendirilmektedir. Mevcut sürümde reklam aktif değildir. Reklamlı bir sürümden önce sağlayıcılar, veri erişimi, toplama veya paylaşma, izin ve çocuk güvenliği önlemleri açıklanarak bu politika ve mağaza beyanları güncellenecektir.",
    sections: [
      ["1. Uygulama hakkında", "<p>Zuzu: Bloomflight, sevimli bir çizgi arıyı altı bahçeden geçirdiğiniz; uçtuğunuz, havada kaldığınız, çiçek açtırdığınız, nektar yönettiğiniz, güçlendirme topladığınız ve rekor kovaladığınız tek dokunuşlu bir arcade oyunudur.</p><p>Genel izleyici içindir, <strong>6 yaş ve üzeri</strong> için önerilir ve yalnızca çocuklara yönelik değildir.</p>"],
      ["2. Kişisel veriler ve Google Play Games", "<p>Zuzu: Bloomflight ad, e-posta, telefon, konum, kişiler, fotoğraflar, medya veya ödeme bilgilerini <strong>istemez ve toplamaz</strong>.</p><p>Google Play Games girişini veya çevrimiçi liderlik tablosunu seçerseniz Google hesabınızı, oyuncu kimliğinizi, profilinizi ve skorunuzu kendi politikasına göre işleyebilir. Oyun yalnızca bu isteğe bağlı özellik için skor gönderir ve tabloyu okur.</p>"],
      ["3. Yalnızca cihazda saklanan bilgiler", "<p>Yerel olarak şunlar saklanır:</p><ul><li>en iyi skor, oyun sayısı, açan çiçekler ve ulaşılan en uzak bahçe;</li><li>dil, ses, müzik, isteğe bağlı titreşim ve parlak mod.</li></ul><p>İlk açılışta cihaz dili yerel olarak okunabilir. Hiçbir bilgi cihazdan çıkmaz veya BieMTech'e ulaşmaz.</p>"],
      ["4. Çevrimdışı kullanım, bağlantı ve izinler", "<p>Ana oyun çevrimdışı çalışır. İnternet yalnızca isteğe bağlı Google Play Games girişi ve liderlik tablosu için kullanılır. Oyun titreşim kullanabilir; konum, kamera, mikrofon, kişiler, fotoğraflar, harici depolama, bildirim veya başka hassas izin istemez.</p>"],
      ["5. Çocuklar ve yaş önerisi", "<p>Kayıt, sohbet, sosyal profil, kullanıcı içeriği, reklam, kumar veya satın alma yoktur. Dost bir arı, çiçekler, hayali engeller ve koşu sonunda kısa, grafik olmayan bir çarpışma vardır; kan, gerçekçi şiddet veya korkutucu içerik yoktur.</p><p>Zamanlama, kaynak yönetimi ve hızlı tepki gerektirdiğinden BieMTech <strong>6+</strong> önerir ve geniş izleyiciye uygun görür. Resmî mağaza dereceleri bölgesel olarak verilir.</p>"],
      ["6. Reklam, analiz ve üçüncü taraflar", "<p>Mevcut sürümde reklam veya analiz, izleme, çökme raporu, bulut kaydı, sosyal ağ ya da satın alma için üçüncü taraf SDK yoktur. Google Play Games tek isteğe bağlı çevrimiçi entegrasyondur ve Google politikalarına tabidir. Google Play mağaza ve cihaz verilerini ayrıca işleyebilir.</p>"],
      ["7. Saklama, güvenlik ve silme", "<p>Ayarlar ve istatistikler silinene kadar cihazda kalır. Android'de uygulama depolamasını temizleyin veya uygulamayı kaldırın. BieMTech sunucusuna veri gönderilmediğinden sunucu silme talebi gerekmez.</p>"],
      ["8. Değişiklikler ve iletişim", "<p>Uygulama veya veri uygulamaları değişirse politika güncellenebilir. Yeni metin ilgili sürümden önce yayımlanır.</p><p>İletişim:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  ar: {
    dir: "rtl", back: "سياسات خصوصية BieMTech →", subtitle: "سياسة الخصوصية", audience: "موصى به لعمر 6+ · لعبة لجمهور عام", rights: "جميع الحقوق محفوظة.", app: "التطبيق", pkg: "الحزمة", updated: "آخر تحديث", date: "30 أغسطس 2026",
    summary: "<strong>باختصار:</strong> يحتفظ Zuzu: Bloomflight بتقدم اللعبة الأساسي والتفضيلات على الجهاز ولا يبيع البيانات الشخصية. تعمل اللعبة الأساسية دون اتصال. يستخدم تسجيل الدخول ولوحة الصدارة الاختياريان في Google Play Games خدمة Google فقط عند اختيارك لهما. لا توجد إعلانات أو تحليلات أو مشتريات.",
    futureAds: "<strong>تغيير مستقبلي محتمل:</strong> يجري النظر في إضافة الإعلانات إلى إصدار مستقبلي. لا توجد إعلانات نشطة حالياً. قبل أي إصدار يتضمن إعلانات، ستُحدّث هذه السياسة وإقرارات المتجر لتحديد المزودين ووصف الوصول إلى البيانات أو جمعها أو مشاركتها ومتطلبات الموافقة وحماية الأطفال.",
    sections: [
      ["1. حول التطبيق", "<p>Zuzu: Bloomflight لعبة أركيد بلمسة واحدة تقود فيها نحلة كرتونية ودودة عبر ست حدائق، وتطير وتحلق في المكان وتفتح الأزهار وتدير الرحيق وتجمع التعزيزات وتسعى إلى رقم قياسي.</p><p>هي لعبة لجمهور عام، موصى بها لمن هم <strong>بعمر 6 سنوات فأكثر</strong>، وليست مصممة حصراً للأطفال.</p>"],
      ["2. البيانات الشخصية وGoogle Play Games", "<p>لا يطلب Zuzu: Bloomflight ولا يجمع اسمك أو بريدك أو هاتفك أو موقعك أو جهات اتصالك أو صورك أو وسائطك أو بيانات الدفع.</p><p>إذا اخترت تسجيل الدخول أو لوحة الصدارة في Google Play Games فقد تعالج Google حسابك ومعرّف اللاعب والملف والنتيجة وفق سياستها. ترسل اللعبة النتائج وتقرأ اللوحة فقط لهذه الميزة الاختيارية.</p>"],
      ["3. معلومات محفوظة على الجهاز فقط", "<p>يحفظ محلياً:</p><ul><li>أفضل نتيجة وعدد اللعبات والأزهار المفتوحة وأبعد حديقة؛</li><li>اللغة والصوت والموسيقى والاهتزاز الاختياري والوضع الساطع.</li></ul><p>عند التشغيل الأول قد تُقرأ لغة الجهاز محلياً. لا تغادر البيانات الجهاز ولا تتاح لـ BieMTech.</p>"],
      ["4. اللعب دون اتصال والاتصال والأذونات", "<p>تعمل اللعبة الأساسية دون اتصال. يُستخدم الإنترنت فقط لتسجيل الدخول ولوحة الصدارة الاختياريين في Google Play Games. قد تستخدم اللعبة الاهتزاز، ولا تطلب الموقع أو الكاميرا أو الميكروفون أو جهات الاتصال أو الصور أو التخزين الخارجي أو الإشعارات أو أذونات حساسة أخرى.</p>"],
      ["5. الأطفال والعمر", "<p>لا يوجد تسجيل أو دردشة أو ملف اجتماعي أو محتوى مستخدم أو إعلانات أو قمار أو مشتريات. يظهر فقط نحل ودود وزهور وعوائق خيالية واصطدام قصير غير صريح، بلا دماء أو عنف واقعي أو محتوى مخيف.</p><p>بسبب التوقيت وإدارة الموارد وسرعة الاستجابة توصي BieMTech بعمر <strong>6+</strong> وترى اللعبة مناسبة لجمهور واسع. تحدد الجهات الإقليمية التصنيفات الرسمية.</p>"],
      ["6. الإعلانات والتحليلات والجهات الخارجية", "<p>لا يحتوي الإصدار الحالي على إعلانات أو حزم خارجية للتحليلات أو التتبع أو تقارير الأعطال أو الحفظ السحابي أو الشبكات الاجتماعية أو المشتريات. Google Play Games هو التكامل الاختياري الوحيد عبر الإنترنت ويخضع لسياسات Google. وقد يعالج Google Play بيانات المتجر والجهاز بشكل منفصل.</p>"],
      ["7. الاحتفاظ والأمان والحذف", "<p>تبقى الإعدادات والإحصاءات على الجهاز حتى حذفها. امسح مساحة التطبيق في Android أو أزل التطبيق لحذف كل شيء. لا يلزم طلب حذف من الخادم لأنه لا تُرسل بيانات إلى BieMTech.</p>"],
      ["8. التغييرات والتواصل", "<p>قد نحدّث السياسة إذا تغير التطبيق أو ممارسات البيانات، وستُنشر المراجعة قبل الإصدار المعني.</p><p>للتواصل:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  hi: {
    dir: "ltr", back: "← BieMTech गोपनीयता नीतियाँ", subtitle: "गोपनीयता नीति", audience: "6+ वर्ष के लिए अनुशंसित · सामान्य दर्शकों का खेल", rights: "सर्वाधिकार सुरक्षित।", app: "ऐप", pkg: "पैकेज", updated: "अंतिम अपडेट", date: "30 अगस्त 2026",
    summary: "<strong>संक्षेप में:</strong> Zuzu: Bloomflight मुख्य प्रगति और सेटिंग डिवाइस पर रखता है और निजी डेटा नहीं बेचता। मुख्य खेल ऑफलाइन चलता है। वैकल्पिक Google Play Games साइन-इन और लीडरबोर्ड केवल आपके चुनने पर Google सेवा का उपयोग करते हैं। कोई विज्ञापन, एनालिटिक्स या खरीदारी नहीं है।",
    futureAds: "<strong>संभावित भविष्य बदलाव:</strong> भविष्य के संस्करण में विज्ञापन जोड़ने पर विचार किया जा रहा है। वर्तमान संस्करण में विज्ञापन सक्रिय नहीं हैं। विज्ञापन वाले संस्करण से पहले इस नीति और स्टोर घोषणाओं में प्रदाता, डेटा पहुँच/संग्रह/साझाकरण, सहमति और बाल-सुरक्षा उपाय बताए जाएँगे।",
    sections: [
      ["1. ऐप के बारे में", "<p>Zuzu: Bloomflight एक-टच आर्केड गेम है जिसमें खिलाड़ी एक दोस्ताना कार्टून मधुमक्खी को छह बगीचों से ले जाता है, उड़ता और मँडराता है, फूल खिलाता है, नेक्टर सँभालता है, पावर-अप लेता है और रिकॉर्ड बनाता है।</p><p>यह सामान्य दर्शकों का गेम है, <strong>6 वर्ष और ऊपर</strong> के लिए अनुशंसित है और केवल बच्चों के लिए नहीं बनाया गया।</p>"],
      ["2. निजी डेटा और Google Play Games", "<p>Zuzu: Bloomflight आपका नाम, ईमेल, फोन, स्थान, संपर्क, फोटो, मीडिया या भुगतान जानकारी <strong>नहीं मांगता या इकट्ठा करता</strong>।</p><p>Google Play Games साइन-इन या ऑनलाइन लीडरबोर्ड चुनने पर Google अपनी नीति के अनुसार खाता, खिलाड़ी आईडी, प्रोफाइल और स्कोर संसाधित कर सकता है। खेल केवल इस वैकल्पिक सुविधा के लिए स्कोर भेजता और सूची पढ़ता है।</p>"],
      ["3. केवल डिवाइस पर जानकारी", "<p>स्थानीय रूप से सहेजा जाता है:</p><ul><li>सर्वश्रेष्ठ स्कोर, खेलों की संख्या, खिले फूल और सबसे दूर का बगीचा;</li><li>भाषा, ध्वनि, संगीत, वैकल्पिक कंपन और ब्राइट मोड।</li></ul><p>पहली बार डिवाइस भाषा स्थानीय रूप से पढ़ी जा सकती है। जानकारी डिवाइस से बाहर नहीं जाती और BieMTech को उपलब्ध नहीं होती।</p>"],
      ["4. ऑफलाइन उपयोग, कनेक्शन और अनुमतियाँ", "<p>मुख्य खेल ऑफलाइन चलता है। इंटरनेट केवल वैकल्पिक Google Play Games साइन-इन और लीडरबोर्ड के लिए उपयोग होता है। खेल हैप्टिक प्रतिक्रिया के लिए कंपन का उपयोग कर सकता है और स्थान, कैमरा, माइक्रोफोन, संपर्क, फोटो, बाहरी स्टोरेज, सूचनाएँ या अन्य संवेदनशील अनुमति नहीं मांगता।</p>"],
      ["5. बच्चे और आयु", "<p>पंजीकरण, चैट, सामाजिक प्रोफाइल, उपयोगकर्ता सामग्री, विज्ञापन, जुआ या खरीद नहीं है। दोस्ताना मधुमक्खी, फूल, काल्पनिक बाधाएँ और अंत में छोटी गैर-ग्राफिक टक्कर है; खून, वास्तविक हिंसा या डरावनी सामग्री नहीं।</p><p>समय, संसाधन और तेज प्रतिक्रिया के कारण BieMTech <strong>6+</strong> की अनुशंसा करता है और इसे व्यापक दर्शकों के लिए उचित मानता है। आधिकारिक रेटिंग क्षेत्रीय संस्थाएँ देती हैं।</p>"],
      ["6. विज्ञापन, एनालिटिक्स और तृतीय पक्ष", "<p>वर्तमान संस्करण में विज्ञापन या एनालिटिक्स, ट्रैकिंग, क्रैश रिपोर्ट, क्लाउड सेव, सोशल नेटवर्क या खरीदारी के लिए तृतीय-पक्ष SDK नहीं है। Google Play Games एकमात्र वैकल्पिक ऑनलाइन एकीकरण है और Google की नीतियों के अधीन है। Google Play स्टोर और डिवाइस डेटा अलग से संसाधित कर सकता है।</p>"],
      ["7. प्रतिधारण, सुरक्षा और हटाना", "<p>सेटिंग और आँकड़े हटाए जाने तक डिवाइस पर रहते हैं। Android में ऐप स्टोरेज साफ करें या ऐप अनइंस्टॉल करें। BieMTech सर्वर को डेटा नहीं जाता, इसलिए सर्वर अनुरोध आवश्यक नहीं।</p>"],
      ["8. बदलाव और संपर्क", "<p>ऐप या डेटा अभ्यास बदलने पर नीति अपडेट हो सकती है। संशोधन संबंधित रिलीज से पहले प्रकाशित होगा।</p><p>संपर्क:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  id: {
    dir: "ltr", back: "← Kebijakan Privasi BieMTech", subtitle: "Kebijakan Privasi", audience: "Disarankan untuk usia 6+ · Game untuk audiens umum", rights: "Hak cipta dilindungi.", app: "Aplikasi", pkg: "Paket", updated: "Terakhir diperbarui", date: "30 Agustus 2026",
    summary: "<strong>Singkatnya:</strong> Zuzu: Bloomflight menyimpan progres utama dan preferensi di perangkat serta tidak menjual data pribadi. Game utama berjalan offline. Login dan papan peringkat Google Play Games yang opsional hanya memakai layanan Google saat Anda memilihnya. Tidak ada iklan, analitik, atau pembelian.",
    futureAds: "<strong>Kemungkinan perubahan:</strong> Iklan sedang dipertimbangkan untuk versi mendatang. Iklan tidak aktif pada versi saat ini. Sebelum versi beriklan, kebijakan dan deklarasi toko akan diperbarui untuk menyebut penyedia, akses/pengumpulan/pembagian data, persetujuan, dan perlindungan anak.",
    sections: [
      ["1. Tentang aplikasi", "<p>Zuzu: Bloomflight adalah game arkade satu sentuhan: pemain memandu lebah kartun yang ramah melewati enam taman, terbang, melayang, memekarkan bunga, mengelola nektar, mengambil power-up, dan mengejar skor.</p><p>Game ini untuk audiens umum, disarankan bagi <strong>usia 6+</strong>, dan tidak dibuat khusus untuk anak-anak.</p>"],
      ["2. Data pribadi dan Google Play Games", "<p>Zuzu: Bloomflight <strong>tidak meminta atau mengumpulkan</strong> nama, email, telepon, lokasi, kontak, foto, media, atau data pembayaran.</p><p>Jika Anda memilih login atau papan peringkat Google Play Games, Google dapat memproses akun, ID pemain, profil, dan skor menurut kebijakannya. Game hanya mengirim skor dan membaca papan untuk fitur opsional tersebut.</p>"],
      ["3. Informasi hanya di perangkat", "<p>Yang disimpan lokal:</p><ul><li>skor terbaik, jumlah permainan, bunga mekar, dan taman terjauh;</li><li>bahasa, suara, musik, getar opsional, dan mode terang.</li></ul><p>Saat pertama dibuka, bahasa perangkat dapat dibaca secara lokal. Tidak ada informasi yang keluar atau tersedia bagi BieMTech.</p>"],
      ["4. Penggunaan offline, koneksi, dan izin", "<p>Game utama berjalan offline. Internet hanya digunakan untuk login dan papan peringkat Google Play Games yang opsional. Game dapat memakai getaran dan tidak meminta lokasi, kamera, mikrofon, kontak, foto, penyimpanan eksternal, notifikasi, atau izin sensitif lain.</p>"],
      ["5. Anak-anak dan usia", "<p>Tidak ada pendaftaran, obrolan, profil sosial, konten pengguna, iklan, perjudian, atau pembelian. Hanya ada lebah ramah, bunga, rintangan fantasi, dan benturan singkat tanpa grafis; tanpa darah, kekerasan realistis, atau konten menakutkan.</p><p>Karena membutuhkan waktu, pengelolaan sumber daya, dan reaksi cepat, BieMTech menyarankan <strong>usia 6+</strong> dan menilai game sesuai untuk audiens luas. Rating resmi ditentukan secara regional.</p>"],
      ["6. Iklan, analitik, dan pihak ketiga", "<p>Versi saat ini tidak berisi iklan atau SDK pihak ketiga untuk analitik, pelacakan, laporan crash, penyimpanan cloud, jejaring sosial, atau pembelian. Google Play Games adalah satu-satunya integrasi online opsional dan tunduk pada kebijakan Google. Google Play juga dapat memproses data toko dan perangkat secara terpisah.</p>"],
      ["7. Penyimpanan, keamanan, dan penghapusan", "<p>Pengaturan dan statistik tetap di perangkat hingga dihapus. Bersihkan penyimpanan aplikasi di Android atau uninstall aplikasi. Karena data tidak dikirim ke server BieMTech, permintaan penghapusan server tidak diperlukan.</p>"],
      ["8. Perubahan dan kontak", "<p>Kebijakan dapat diperbarui jika aplikasi atau praktik data berubah. Revisi akan diterbitkan sebelum rilis terkait.</p><p>Kontak:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  zh: {
    dir: "ltr", back: "← BieMTech 隐私政策", subtitle: "隐私政策", audience: "建议6岁以上 · 普通受众游戏", rights: "版权所有。", app: "应用", pkg: "软件包", updated: "最后更新", date: "2026年8月30日",
    summary: "<strong>简而言之：</strong>Zuzu: Bloomflight 将核心进度和偏好保存在设备上，不出售个人数据。核心游戏可离线运行。只有在您选择时，可选的 Google Play Games 登录和排行榜才会使用 Google 服务。没有广告、分析或购买。",
    futureAds: "<strong>未来可能的变化：</strong>未来版本正在考虑加入广告。当前版本尚未启用广告。发布含广告版本前，本政策和应用商店声明将更新，以说明服务商、数据访问/收集/共享以及所需的同意和儿童保护措施。",
    sections: [
      ["1. 关于本应用", "<p>Zuzu: Bloomflight 是一款单触街机游戏。玩家带领友好的卡通蜜蜂穿越六座花园，飞行、悬停、让花朵绽放、管理花蜜、收集道具并挑战高分。</p><p>本游戏面向普通受众，建议<strong>6岁以上</strong>游玩，并非专为儿童设计。</p>"],
      ["2. 个人数据与 Google Play Games", "<p>Zuzu: Bloomflight <strong>不会要求或收集</strong>您的姓名、邮箱、电话、位置、联系人、照片、媒体或付款信息。</p><p>如果您选择 Google Play Games 登录或在线排行榜，Google 可按其政策处理账户、玩家标识、资料和分数。游戏仅为该可选功能提交分数并读取排行榜。</p>"],
      ["3. 仅存储在设备上的信息", "<p>游戏本地保存：</p><ul><li>最高分、游戏次数、绽放花朵数和到达的最远花园；</li><li>语言、音效、音乐、可选振动和明亮模式。</li></ul><p>首次启动时可能在本地读取设备语言。信息不会离开设备，BieMTech 也无法访问。</p>"],
      ["4. 离线使用、联网与权限", "<p>核心游戏可离线运行。互联网仅用于可选的 Google Play Games 登录和排行榜。游戏可使用振动提供触觉反馈，不要求位置、相机、麦克风、联系人、照片、外部存储、通知或其他敏感权限。</p>"],
      ["5. 儿童与年龄建议", "<p>没有注册、聊天、社交资料、用户内容、广告、赌博或购买。内容只有友好蜜蜂、花朵、幻想花园障碍和结束时短暂的非写实碰撞；没有血腥、写实暴力或恐怖内容。</p><p>由于需要时机、资源管理和快速反应，BieMTech 建议<strong>6岁以上</strong>，同时认为适合广泛受众。官方商店分级由地区机构另行确定。</p>"],
      ["6. 广告、分析与第三方", "<p>当前版本不含广告，也没有用于分析、跟踪、崩溃报告、云存档、社交网络或购买的第三方 SDK。Google Play Games 是唯一的可选在线集成，并受 Google 政策约束。Google Play 也可单独处理商店和设备数据。</p>"],
      ["7. 保留、安全与删除", "<p>设置和统计保留在设备上直至删除。可在 Android 中清除应用存储或卸载应用。数据不会发送到 BieMTech 服务器，因此无需服务器删除请求。</p>"],
      ["8. 变更与联系", "<p>若应用或数据做法改变，我们可能更新本政策。修订版会在相关版本发布前公布。</p><p>联系：</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  }
};
