const ZUZU_POLICY = {
  en: {
    dir: "ltr", back: "← BieMTech Privacy Policies", subtitle: "Privacy Policy", audience: "Recommended for ages 6+ · General-audience game", rights: "All rights reserved.", app: "Application", pkg: "Package", updated: "Last updated", date: "August 3, 2026",
    summary: "<strong>In short:</strong> Zuzu: Bloomflight <strong>does not collect, share, sell, or transmit</strong> personal data. The current version works offline, contains no advertising or analytics, and keeps game progress and preferences only on your device.",
    futureAds: "<strong>Possible future change:</strong> Advertising is being considered for a future version. Advertising is not active in the current version. Before any ad-enabled release, this policy and the app-store declarations will be updated to name the provider(s), describe any data access, collection, or sharing, and explain required consent and child-safety controls.",
    sections: [
      ["1. About This App", "<p>Zuzu: Bloomflight is a one-touch arcade game in which players guide a friendly cartoon bee through six changing gardens, tap to fly, hold to hover, bloom flowers, manage nectar, collect power-ups, build combos, and chase a high score.</p><p>It is a general-audience game recommended for players <strong>aged 6 and up</strong>. It is not designed exclusively for children.</p>"],
      ["2. Personal Data", "<p>Zuzu: Bloomflight <strong>does not access, collect, transmit, share, or sell personal or sensitive data</strong>. It does not ask for a name, email address, phone number, account, login, location, contacts, photos, media, or payment information.</p>"],
      ["3. Information Stored Only on Your Device", "<p>The game stores a small local configuration file containing:</p><ul><li>best score, games played, flowers bloomed, and furthest garden reached;</li><li>language, sound, music, optional vibration, and bright-mode preferences.</li></ul><p>On first launch, the device language may be read locally to choose a supported interface language. None of this information leaves the device or is available to BieMTech.</p>"],
      ["4. Offline Use and Permissions", "<p>The current Android version works offline and <strong>does not request Internet access</strong>. It requests only the Android vibration permission for optional haptic feedback. It does not request location, camera, microphone, contacts, external storage, notifications, or other sensitive permissions.</p>"],
      ["5. Children and Age Guidance", "<p>The game has no registration, chat, social profile, user-generated content, advertising, gambling, or purchases. Its content consists of a friendly cartoon bee, flowers, fantasy garden obstacles, and a brief non-graphic collision when a run ends. There is no blood, gore, realistic violence, or frightening content.</p><p>Because success requires timing, resource management, and quick reactions, BieMTech recommends <strong>ages 6 and up</strong> while considering the game suitable for a broad audience. Official store ratings are assigned separately by regional rating authorities.</p>"],
      ["6. Advertising, Analytics, and Third Parties", "<p>The current version contains no ads and no third-party SDKs for analytics, tracking, crash reporting, accounts, cloud saves, social features, or in-app purchases. Advertising may be considered later, but it will not be introduced under this policy without first updating the disclosures and any required consent or child-safety measures. The store or platform may separately process its own data under its own policy.</p>"],
      ["7. Retention, Security, and Deletion", "<p>Local settings and game statistics remain on the device until you delete them. You can remove all local data by clearing the app's storage in Android Settings or uninstalling the app. Because no data is sent to a BieMTech server, no server-side deletion request is necessary.</p>"],
      ["8. Changes and Contact", "<p>We may update this policy if the app or its data practices change. A revised policy will be published before the relevant release.</p><p>Questions can be sent to BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  az: {
    dir: "ltr", back: "← BieMTech Məxfilik Siyasətləri", subtitle: "Məxfilik Siyasəti", audience: "6+ yaş üçün tövsiyə olunur · Ümumi auditoriya oyunu", rights: "Bütün hüquqlar qorunur.", app: "Tətbiq", pkg: "Paket", updated: "Son yenilənmə", date: "3 avqust 2026",
    summary: "<strong>Qısa olaraq:</strong> Zuzu: Bloomflight şəxsi məlumatları <strong>toplamır, paylaşmır, satmır və ötürmür</strong>. Cari versiya oflayn işləyir, reklam və analitika ehtiva etmir, oyun irəliləyişi ilə seçimləri yalnız cihazınızda saxlayır.",
    futureAds: "<strong>Gələcəkdə mümkün dəyişiklik:</strong> Gələcək versiyalardan birində reklam əlavə edilməsi nəzərdən keçirilir. Cari versiyada reklam aktiv deyil. Reklamlı versiya yayımlanmazdan əvvəl provayderlər, məlumatlara çıxış, toplama və ya paylaşma, tələb olunan razılıq və uşaq təhlükəsizliyi tədbirləri açıqlanmaqla bu siyasət və tətbiq mağazası bəyannamələri yenilənəcək.",
    sections: [
      ["1. Tətbiq haqqında", "<p>Zuzu: Bloomflight oyunçunun mehriban cizgi arısı Zuzunu dəyişən altı bağdan keçirdiyi bir toxunuşlu arkada oyunudur. Oyunçu uçmaq üçün toxunur, havada qalmaq üçün basıb saxlayır, çiçəkləri açır, nektarı idarə edir, gücləndiricilər toplayır, kombolar qurur və rekord qazanmağa çalışır.</p><p>Ümumi auditoriya üçün nəzərdə tutulub və <strong>6 yaşdan yuxarı</strong> oyunçulara tövsiyə olunur. Yalnız uşaqlar üçün hazırlanmayıb.</p>"],
      ["2. Şəxsi məlumatlar", "<p>Zuzu: Bloomflight <strong>şəxsi və ya həssas məlumatlara çıxmır, onları toplamır, ötürmür, paylaşmır və satmır</strong>. Ad, e-poçt, telefon, hesab, giriş, məkan, kontakt, foto, media və ya ödəniş məlumatı istəmir.</p>"],
      ["3. Yalnız cihazda saxlanılan məlumat", "<p>Oyun kiçik lokal konfiqurasiya faylında bunları saxlayır:</p><ul><li>ən yaxşı xal, oyun sayı, açılmış çiçəklər və çatılmış ən uzaq bağ;</li><li>dil, səs, musiqi, seçimli vibrasiya və parlaq rejim seçimləri.</li></ul><p>İlk açılışda dəstəklənən interfeys dilini seçmək üçün cihazın dili lokal olaraq oxuna bilər. Bu məlumatların heç biri cihazdan çıxmır və BieMTech üçün əlçatan deyil.</p>"],
      ["4. Oflayn istifadə və icazələr", "<p>Cari Android versiyası oflayn işləyir və <strong>internet icazəsi istəmir</strong>. Yalnız seçimli haptik geribildirim üçün Android vibrasiya icazəsini istəyir. Məkan, kamera, mikrofon, kontaktlar, xarici yaddaş, bildiriş və ya başqa həssas icazə istəmir.</p>"],
      ["5. Uşaqlar və yaş tövsiyəsi", "<p>Oyunda qeydiyyat, çat, sosial profil, istifadəçi məzmunu, reklam, qumar və satınalma yoxdur. Məzmun mehriban cizgi arısı, çiçəklər, fantastik bağ maneələri və gediş bitəndə qısa, qeyri-qrafik toqquşmadan ibarətdir. Qan, real zorakılıq və qorxuducu məzmun yoxdur.</p><p>Uğur zamanlama, resurs idarəsi və sürətli reaksiya tələb etdiyinə görə BieMTech oyunu <strong>6 yaş və yuxarı</strong> üçün tövsiyə edir və geniş auditoriyaya uyğun sayır. Rəsmi mağaza reytinqi regional qurumlar tərəfindən ayrıca verilir.</p>"],
      ["6. Reklam, analitika və üçüncü tərəflər", "<p>Cari versiyada reklam və analitika, izləmə, xəta hesabatı, hesab, bulud yaddaşı, sosial funksiyalar və tətbiqdaxili satınalma üçün üçüncü tərəf SDK-sı yoxdur. Reklam sonradan nəzərdən keçirilə bilər, lakin açıqlamalar və tələb olunan razılıq və uşaq təhlükəsizliyi tədbirləri yenilənmədən bu siyasət altında əlavə edilməyəcək. Tətbiq mağazası öz siyasətinə əsasən ayrıca məlumat emal edə bilər.</p>"],
      ["7. Saxlama, təhlükəsizlik və silinmə", "<p>Lokal seçimlər və oyun statistikası siz silənədək cihazda qalır. Android Ayarlarında tətbiq yaddaşını təmizləməklə və ya tətbiqi silməklə bütün lokal məlumatları silə bilərsiniz. BieMTech serverinə məlumat göndərilmədiyi üçün server tərəfli silinmə sorğusu lazım deyil.</p>"],
      ["8. Dəyişikliklər və əlaqə", "<p>Tətbiq və ya məlumat təcrübəsi dəyişərsə, bu siyasəti yeniləyə bilərik. Yenilənmiş siyasət aidiyyəti versiyadan əvvəl yayımlanacaq.</p><p>Suallar üçün BieMTech ilə əlaqə saxlayın:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  es: {
    dir: "ltr", back: "← Políticas de privacidad de BieMTech", subtitle: "Política de privacidad", audience: "Recomendado para mayores de 6 años · Juego para público general", rights: "Todos los derechos reservados.", app: "Aplicación", pkg: "Paquete", updated: "Última actualización", date: "3 de agosto de 2026",
    summary: "<strong>En resumen:</strong> Zuzu: Bloomflight <strong>no recopila, comparte, vende ni transmite</strong> datos personales. La versión actual funciona sin conexión, no tiene publicidad ni analíticas y guarda el progreso y las preferencias solo en el dispositivo.",
    futureAds: "<strong>Posible cambio futuro:</strong> Se está considerando añadir publicidad en una versión futura. No hay publicidad activa actualmente. Antes de una versión con anuncios se actualizarán esta política y las declaraciones de la tienda para identificar proveedores, describir el acceso, la recopilación o el intercambio de datos y explicar el consentimiento y las medidas de protección infantil.",
    sections: [
      ["1. Sobre la aplicación", "<p>Zuzu: Bloomflight es un juego arcade de un toque en el que guías a una abeja de dibujos animados por seis jardines, vuelas, flotas, haces florecer plantas, gestionas néctar, recoges potenciadores y buscas récords.</p><p>Es un juego para público general recomendado para <strong>mayores de 6 años</strong>, no diseñado exclusivamente para niños.</p>"],
      ["2. Datos personales", "<p>Zuzu: Bloomflight <strong>no accede, recopila, transmite, comparte ni vende datos personales o sensibles</strong>. No solicita nombre, correo, teléfono, cuenta, inicio de sesión, ubicación, contactos, fotos, archivos multimedia ni datos de pago.</p>"],
      ["3. Información guardada solo en el dispositivo", "<p>El juego guarda localmente:</p><ul><li>récord, partidas jugadas, flores abiertas y jardín más lejano;</li><li>idioma, sonido, música, vibración opcional y modo brillante.</li></ul><p>Al abrirlo por primera vez puede leer localmente el idioma del dispositivo. Nada sale del dispositivo ni está disponible para BieMTech.</p>"],
      ["4. Uso sin conexión y permisos", "<p>La versión Android actual funciona sin conexión y <strong>no solicita Internet</strong>. Solo solicita permiso de vibración para la respuesta háptica opcional. No solicita ubicación, cámara, micrófono, contactos, almacenamiento externo, notificaciones ni otros permisos sensibles.</p>"],
      ["5. Niños y orientación de edad", "<p>No hay registro, chat, perfil social, contenido de usuarios, publicidad, apuestas ni compras. Solo aparecen una abeja amistosa, flores, obstáculos de fantasía y una colisión breve y no gráfica al terminar. No hay sangre, violencia realista ni contenido aterrador.</p><p>Por el ritmo, la gestión de recursos y los reflejos necesarios, BieMTech recomienda <strong>6 años o más</strong> y lo considera apto para un público amplio. Las clasificaciones oficiales dependen de cada región.</p>"],
      ["6. Publicidad, analíticas y terceros", "<p>La versión actual no incluye anuncios ni SDK de terceros para analíticas, seguimiento, fallos, cuentas, nube, funciones sociales o compras. La publicidad podrá estudiarse más adelante, pero antes se actualizarán las declaraciones y las medidas de consentimiento y protección infantil. La tienda puede tratar sus propios datos según su política.</p>"],
      ["7. Conservación, seguridad y eliminación", "<p>Los ajustes y estadísticas permanecen en el dispositivo hasta que los elimines. Puedes borrar todo limpiando el almacenamiento de la app en Android o desinstalándola. Como no se envían datos a servidores de BieMTech, no hace falta solicitar su eliminación.</p>"],
      ["8. Cambios y contacto", "<p>Podemos actualizar esta política si cambian la aplicación o sus prácticas. La versión revisada se publicará antes del cambio correspondiente.</p><p>Contacto:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  pt: {
    dir: "ltr", back: "← Políticas de Privacidade BieMTech", subtitle: "Política de Privacidade", audience: "Recomendado para maiores de 6 anos · Jogo para público geral", rights: "Todos os direitos reservados.", app: "Aplicativo", pkg: "Pacote", updated: "Última atualização", date: "3 de agosto de 2026",
    summary: "<strong>Em resumo:</strong> Zuzu: Bloomflight <strong>não coleta, compartilha, vende nem transmite</strong> dados pessoais. A versão atual funciona offline, não tem anúncios ou análises e guarda progresso e preferências apenas no dispositivo.",
    futureAds: "<strong>Possível mudança futura:</strong> A inclusão de publicidade está sendo considerada para uma versão futura. Não há anúncios ativos na versão atual. Antes de qualquer versão com anúncios, esta política e as declarações da loja serão atualizadas com fornecedores, acesso, coleta ou compartilhamento de dados e medidas de consentimento e proteção infantil.",
    sections: [
      ["1. Sobre o aplicativo", "<p>Zuzu: Bloomflight é um jogo arcade de um toque no qual você guia uma abelha amigável por seis jardins, toca para voar, segura para pairar, abre flores, gerencia néctar, coleta poderes e busca recordes.</p><p>É um jogo para público geral recomendado para <strong>maiores de 6 anos</strong>, não feito exclusivamente para crianças.</p>"],
      ["2. Dados pessoais", "<p>Zuzu: Bloomflight <strong>não acessa, coleta, transmite, compartilha nem vende dados pessoais ou sensíveis</strong>. Não pede nome, e-mail, telefone, conta, login, localização, contatos, fotos, mídia ou pagamento.</p>"],
      ["3. Informações apenas no dispositivo", "<p>O jogo guarda localmente:</p><ul><li>recorde, partidas, flores abertas e jardim mais distante;</li><li>idioma, som, música, vibração opcional e modo brilhante.</li></ul><p>Na primeira abertura, o idioma do dispositivo pode ser lido localmente. Nada sai do aparelho nem fica disponível para a BieMTech.</p>"],
      ["4. Uso offline e permissões", "<p>A versão Android atual funciona offline e <strong>não solicita Internet</strong>. Usa somente a permissão de vibração para retorno tátil opcional. Não pede localização, câmera, microfone, contatos, armazenamento externo, notificações ou outras permissões sensíveis.</p>"],
      ["5. Crianças e idade", "<p>Não há cadastro, chat, perfil social, conteúdo de usuários, anúncios, apostas ou compras. Há apenas uma abelha amigável, flores, obstáculos de fantasia e uma colisão breve e não gráfica ao fim da rodada, sem sangue, violência realista ou conteúdo assustador.</p><p>Por exigir ritmo, gestão de recursos e reação rápida, a BieMTech recomenda <strong>6 anos ou mais</strong> e considera o jogo adequado a um público amplo. As classificações oficiais são definidas regionalmente.</p>"],
      ["6. Publicidade, análises e terceiros", "<p>A versão atual não contém anúncios nem SDKs de terceiros para análises, rastreamento, falhas, contas, nuvem, recursos sociais ou compras. Publicidade pode ser considerada no futuro, mas as declarações, o consentimento e as proteções infantis serão atualizados antes. A loja pode tratar seus próprios dados conforme sua política.</p>"],
      ["7. Retenção, segurança e exclusão", "<p>Configurações e estatísticas ficam no aparelho até serem apagadas. Você pode remover tudo limpando o armazenamento do app no Android ou desinstalando-o. Como não há envio a servidores da BieMTech, não é necessário pedido de exclusão no servidor.</p>"],
      ["8. Alterações e contato", "<p>Podemos atualizar esta política se o aplicativo ou suas práticas mudarem. A revisão será publicada antes da versão relacionada.</p><p>Contato:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  fr: {
    dir: "ltr", back: "← Politiques de confidentialité BieMTech", subtitle: "Politique de confidentialité", audience: "Recommandé dès 6 ans · Jeu grand public", rights: "Tous droits réservés.", app: "Application", pkg: "Paquet", updated: "Dernière mise à jour", date: "3 août 2026",
    summary: "<strong>En bref :</strong> Zuzu: Bloomflight <strong>ne collecte, ne partage, ne vend et ne transmet</strong> aucune donnée personnelle. La version actuelle fonctionne hors ligne, sans publicité ni analyse, et conserve progression et préférences uniquement sur l'appareil.",
    futureAds: "<strong>Évolution future possible :</strong> L'ajout de publicité est envisagé pour une future version. Aucune publicité n'est active actuellement. Avant toute version avec publicité, cette politique et les déclarations de la boutique seront mises à jour pour nommer les fournisseurs, décrire tout accès, collecte ou partage de données, ainsi que le consentement et les protections des enfants.",
    sections: [
      ["1. À propos de l'application", "<p>Zuzu: Bloomflight est un jeu d'arcade à une touche où vous guidez une abeille sympathique dans six jardins, volez, planez, faites éclore des fleurs, gérez le nectar, ramassez des bonus et visez un record.</p><p>Ce jeu grand public est recommandé aux personnes de <strong>6 ans et plus</strong> et n'est pas conçu exclusivement pour les enfants.</p>"],
      ["2. Données personnelles", "<p>Zuzu: Bloomflight <strong>n'accède à aucune donnée personnelle ou sensible, ne la collecte, ne la transmet, ne la partage et ne la vend</strong>. Aucun nom, e-mail, téléphone, compte, connexion, localisation, contact, photo, média ou paiement n'est demandé.</p>"],
      ["3. Informations stockées uniquement sur l'appareil", "<p>Le jeu garde localement :</p><ul><li>record, parties, fleurs écloses et jardin le plus éloigné ;</li><li>langue, son, musique, vibration facultative et mode lumineux.</li></ul><p>Au premier lancement, la langue de l'appareil peut être lue localement. Rien ne quitte l'appareil et BieMTech n'y a pas accès.</p>"],
      ["4. Mode hors ligne et autorisations", "<p>La version Android actuelle fonctionne hors ligne et <strong>ne demande pas Internet</strong>. Elle utilise seulement l'autorisation de vibration pour le retour haptique facultatif. Elle ne demande ni localisation, caméra, microphone, contacts, stockage externe, notifications ni autre autorisation sensible.</p>"],
      ["5. Enfants et âge", "<p>Aucune inscription, discussion, profil social, contenu utilisateur, publicité, jeu d'argent ou achat. Le contenu montre une abeille amicale, des fleurs, des obstacles fantastiques et une brève collision non graphique, sans sang, violence réaliste ni contenu effrayant.</p><p>Le rythme, la gestion des ressources et les réflexes conduisent BieMTech à recommander <strong>6 ans et plus</strong>, tout en jugeant le jeu adapté à un large public. Les classements officiels dépendent des régions.</p>"],
      ["6. Publicité, analyses et tiers", "<p>La version actuelle ne contient aucune publicité ni SDK tiers d'analyse, suivi, rapport de panne, compte, cloud, fonction sociale ou achat. Une publicité pourra être envisagée plus tard, mais les déclarations, consentements et protections des enfants seront mis à jour auparavant. La boutique peut traiter ses propres données selon sa politique.</p>"],
      ["7. Conservation, sécurité et suppression", "<p>Les réglages et statistiques restent sur l'appareil jusqu'à leur suppression. Effacez le stockage de l'application dans Android ou désinstallez-la pour tout supprimer. Aucune demande côté serveur n'est nécessaire, car rien n'est envoyé à BieMTech.</p>"],
      ["8. Modifications et contact", "<p>Nous pouvons mettre à jour cette politique si l'application ou ses pratiques changent. La révision sera publiée avant la version concernée.</p><p>Contact :</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  de: {
    dir: "ltr", back: "← BieMTech-Datenschutzerklärungen", subtitle: "Datenschutzerklärung", audience: "Empfohlen ab 6 Jahren · Spiel für allgemeines Publikum", rights: "Alle Rechte vorbehalten.", app: "Anwendung", pkg: "Paket", updated: "Zuletzt aktualisiert", date: "3. August 2026",
    summary: "<strong>Kurz gesagt:</strong> Zuzu: Bloomflight <strong>erhebt, teilt, verkauft oder überträgt</strong> keine personenbezogenen Daten. Die aktuelle Version läuft offline, enthält keine Werbung oder Analyse und speichert Fortschritt und Einstellungen nur auf dem Gerät.",
    futureAds: "<strong>Mögliche spätere Änderung:</strong> Werbung wird für eine zukünftige Version erwogen. In der aktuellen Version ist keine Werbung aktiv. Vor einer werbefinanzierten Version werden diese Richtlinie und die Store-Angaben aktualisiert: Anbieter, Datenzugriff, Erhebung oder Weitergabe sowie Einwilligungs- und Kinderschutzmaßnahmen werden offengelegt.",
    sections: [
      ["1. Über die App", "<p>Zuzu: Bloomflight ist ein Ein-Tasten-Arcade-Spiel, in dem eine freundliche Cartoon-Biene durch sechs Gärten fliegt, schwebt, Blumen öffnet, Nektar verwaltet, Power-ups sammelt und Rekorde jagt.</p><p>Es ist für allgemeines Publikum und wird ab <strong>6 Jahren</strong> empfohlen. Es richtet sich nicht ausschließlich an Kinder.</p>"],
      ["2. Personenbezogene Daten", "<p>Zuzu: Bloomflight <strong>greift nicht auf personenbezogene oder sensible Daten zu, erhebt, überträgt, teilt oder verkauft sie nicht</strong>. Name, E-Mail, Telefon, Konto, Anmeldung, Standort, Kontakte, Fotos, Medien oder Zahlungsdaten werden nicht abgefragt.</p>"],
      ["3. Nur auf dem Gerät gespeicherte Informationen", "<p>Lokal gespeichert werden:</p><ul><li>Rekord, Spiele, geöffnete Blüten und weitester Garten;</li><li>Sprache, Ton, Musik, optionale Vibration und heller Modus.</li></ul><p>Beim ersten Start kann die Gerätesprache lokal gelesen werden. Nichts verlässt das Gerät oder ist für BieMTech zugänglich.</p>"],
      ["4. Offline-Nutzung und Berechtigungen", "<p>Die aktuelle Android-Version läuft offline und <strong>fordert keinen Internetzugriff an</strong>. Nur die Vibrationsberechtigung dient optionalem haptischem Feedback. Standort, Kamera, Mikrofon, Kontakte, externer Speicher, Benachrichtigungen und andere sensible Rechte werden nicht angefordert.</p>"],
      ["5. Kinder und Altersempfehlung", "<p>Es gibt keine Registrierung, Chats, sozialen Profile, Nutzerinhalte, Werbung, Glücksspiele oder Käufe. Zu sehen sind eine freundliche Biene, Blumen, Fantasiehindernisse und eine kurze, unblutige Kollision am Ende eines Laufs – ohne Blut, realistische Gewalt oder Schreckinhalte.</p><p>Wegen Timing, Ressourcenplanung und Reaktion empfiehlt BieMTech <strong>ab 6 Jahren</strong> und hält das Spiel für ein breites Publikum geeignet. Offizielle Altersfreigaben werden regional vergeben.</p>"],
      ["6. Werbung, Analyse und Dritte", "<p>Die aktuelle Version enthält keine Werbung und keine Drittanbieter-SDKs für Analyse, Tracking, Abstürze, Konten, Cloud, soziale Funktionen oder Käufe. Werbung kann später erwogen werden; Angaben, Einwilligungen und Kinderschutz werden vorher aktualisiert. Der Store kann eigene Daten nach seiner Richtlinie verarbeiten.</p>"],
      ["7. Aufbewahrung, Sicherheit und Löschung", "<p>Einstellungen und Statistiken bleiben bis zur Löschung auf dem Gerät. Löschen Sie den App-Speicher in Android oder deinstallieren Sie die App. Da nichts an BieMTech-Server gesendet wird, ist keine serverseitige Anfrage nötig.</p>"],
      ["8. Änderungen und Kontakt", "<p>Wir können diese Richtlinie bei Änderungen an App oder Datenpraxis aktualisieren. Eine neue Fassung wird vor der betreffenden Version veröffentlicht.</p><p>Kontakt:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  ru: {
    dir: "ltr", back: "← Политики конфиденциальности BieMTech", subtitle: "Политика конфиденциальности", audience: "Рекомендуется с 6 лет · Игра для широкой аудитории", rights: "Все права защищены.", app: "Приложение", pkg: "Пакет", updated: "Последнее обновление", date: "3 августа 2026 г.",
    summary: "<strong>Кратко:</strong> Zuzu: Bloomflight <strong>не собирает, не передаёт, не продаёт и не отправляет</strong> персональные данные. Текущая версия работает офлайн, без рекламы и аналитики, а прогресс и настройки хранятся только на устройстве.",
    futureAds: "<strong>Возможное изменение:</strong> Реклама рассматривается для будущей версии. Сейчас она не активна. До выпуска версии с рекламой политика и декларации магазина будут обновлены: будут названы провайдеры, описаны доступ, сбор или передача данных, согласие и меры защиты детей.",
    sections: [
      ["1. О приложении", "<p>Zuzu: Bloomflight — аркада с управлением одним касанием: игрок ведёт дружелюбную мультяшную пчелу через шесть садов, летает, зависает, раскрывает цветы, управляет нектаром, собирает усиления и ставит рекорды.</p><p>Игра предназначена для широкой аудитории и рекомендуется <strong>с 6 лет</strong>. Она не создана исключительно для детей.</p>"],
      ["2. Персональные данные", "<p>Zuzu: Bloomflight <strong>не получает доступ, не собирает, не передаёт, не делится и не продаёт персональные или чувствительные данные</strong>. Игра не запрашивает имя, email, телефон, аккаунт, вход, местоположение, контакты, фото, медиа или платёжные данные.</p>"],
      ["3. Данные только на устройстве", "<p>Локально сохраняются:</p><ul><li>рекорд, число игр, распустившиеся цветы и самый дальний сад;</li><li>язык, звук, музыка, необязательная вибрация и яркий режим.</li></ul><p>При первом запуске язык устройства может быть прочитан локально. Данные не покидают устройство и недоступны BieMTech.</p>"],
      ["4. Офлайн-режим и разрешения", "<p>Текущая Android-версия работает офлайн и <strong>не запрашивает Интернет</strong>. Разрешение на вибрацию используется только для необязательной тактильной отдачи. Нет запросов к местоположению, камере, микрофону, контактам, внешнему хранилищу, уведомлениям и другим чувствительным разрешениям.</p>"],
      ["5. Дети и возраст", "<p>Нет регистрации, чата, социальных профилей, пользовательского контента, рекламы, азартных игр или покупок. Есть дружелюбная пчела, цветы, фантазийные препятствия и короткое неграфичное столкновение без крови, реалистичного насилия или пугающего контента.</p><p>Из-за требований к времени, ресурсам и реакции BieMTech рекомендует <strong>6+</strong>, считая игру подходящей широкой аудитории. Официальные рейтинги назначаются отдельно по регионам.</p>"],
      ["6. Реклама, аналитика и третьи стороны", "<p>В текущей версии нет рекламы и сторонних SDK аналитики, отслеживания, отчётов о сбоях, аккаунтов, облака, социальных функций или покупок. Реклама может рассматриваться позже, но декларации, согласия и защита детей будут обновлены заранее. Магазин может отдельно обрабатывать свои данные по своей политике.</p>"],
      ["7. Хранение, безопасность и удаление", "<p>Настройки и статистика остаются на устройстве до удаления. Очистите данные приложения в Android или удалите приложение. Так как данные не отправляются на сервер BieMTech, серверный запрос не нужен.</p>"],
      ["8. Изменения и контакты", "<p>Мы можем обновить политику при изменении приложения или работы с данными. Новая версия будет опубликована до соответствующего релиза.</p><p>Контакт:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  tr: {
    dir: "ltr", back: "← BieMTech Gizlilik Politikaları", subtitle: "Gizlilik Politikası", audience: "6+ yaş için önerilir · Genel izleyici oyunu", rights: "Tüm hakları saklıdır.", app: "Uygulama", pkg: "Paket", updated: "Son güncelleme", date: "3 Ağustos 2026",
    summary: "<strong>Kısaca:</strong> Zuzu: Bloomflight kişisel verileri <strong>toplamaz, paylaşmaz, satmaz veya iletmez</strong>. Mevcut sürüm çevrimdışı çalışır, reklam veya analiz içermez; ilerleme ve tercihleri yalnızca cihazda tutar.",
    futureAds: "<strong>Gelecekte olası değişiklik:</strong> İlerideki bir sürüm için reklam değerlendirilmektedir. Mevcut sürümde reklam aktif değildir. Reklamlı bir sürümden önce sağlayıcılar, veri erişimi, toplama veya paylaşma, izin ve çocuk güvenliği önlemleri açıklanarak bu politika ve mağaza beyanları güncellenecektir.",
    sections: [
      ["1. Uygulama hakkında", "<p>Zuzu: Bloomflight, sevimli bir çizgi arıyı altı bahçeden geçirdiğiniz; uçtuğunuz, havada kaldığınız, çiçek açtırdığınız, nektar yönettiğiniz, güçlendirme topladığınız ve rekor kovaladığınız tek dokunuşlu bir arcade oyunudur.</p><p>Genel izleyici içindir, <strong>6 yaş ve üzeri</strong> için önerilir ve yalnızca çocuklara yönelik değildir.</p>"],
      ["2. Kişisel veriler", "<p>Zuzu: Bloomflight <strong>kişisel veya hassas verilere erişmez, bunları toplamaz, iletmez, paylaşmaz veya satmaz</strong>. Ad, e-posta, telefon, hesap, giriş, konum, kişi, fotoğraf, medya veya ödeme bilgisi istemez.</p>"],
      ["3. Yalnızca cihazda saklanan bilgiler", "<p>Yerel olarak şunlar saklanır:</p><ul><li>en iyi skor, oyun sayısı, açan çiçekler ve ulaşılan en uzak bahçe;</li><li>dil, ses, müzik, isteğe bağlı titreşim ve parlak mod.</li></ul><p>İlk açılışta cihaz dili yerel olarak okunabilir. Hiçbir bilgi cihazdan çıkmaz veya BieMTech'e ulaşmaz.</p>"],
      ["4. Çevrimdışı kullanım ve izinler", "<p>Mevcut Android sürümü çevrimdışı çalışır ve <strong>İnternet izni istemez</strong>. Yalnızca isteğe bağlı dokunsal geri bildirim için titreşim izni ister. Konum, kamera, mikrofon, kişiler, harici depolama, bildirim veya başka hassas izin istemez.</p>"],
      ["5. Çocuklar ve yaş önerisi", "<p>Kayıt, sohbet, sosyal profil, kullanıcı içeriği, reklam, kumar veya satın alma yoktur. Dost bir arı, çiçekler, hayali engeller ve koşu sonunda kısa, grafik olmayan bir çarpışma vardır; kan, gerçekçi şiddet veya korkutucu içerik yoktur.</p><p>Zamanlama, kaynak yönetimi ve hızlı tepki gerektirdiğinden BieMTech <strong>6+</strong> önerir ve geniş izleyiciye uygun görür. Resmî mağaza dereceleri bölgesel olarak verilir.</p>"],
      ["6. Reklam, analiz ve üçüncü taraflar", "<p>Mevcut sürümde reklam ya da analiz, izleme, çökme raporu, hesap, bulut, sosyal özellik veya satın alma için üçüncü taraf SDK yoktur. Reklam ileride değerlendirilebilir, ancak beyanlar, izin ve çocuk güvenliği önlemleri önceden güncellenecektir. Mağaza kendi politikasına göre veri işleyebilir.</p>"],
      ["7. Saklama, güvenlik ve silme", "<p>Ayarlar ve istatistikler silinene kadar cihazda kalır. Android'de uygulama depolamasını temizleyin veya uygulamayı kaldırın. BieMTech sunucusuna veri gönderilmediğinden sunucu silme talebi gerekmez.</p>"],
      ["8. Değişiklikler ve iletişim", "<p>Uygulama veya veri uygulamaları değişirse politika güncellenebilir. Yeni metin ilgili sürümden önce yayımlanır.</p><p>İletişim:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  ar: {
    dir: "rtl", back: "سياسات خصوصية BieMTech →", subtitle: "سياسة الخصوصية", audience: "موصى به لعمر 6+ · لعبة لجمهور عام", rights: "جميع الحقوق محفوظة.", app: "التطبيق", pkg: "الحزمة", updated: "آخر تحديث", date: "3 أغسطس 2026",
    summary: "<strong>باختصار:</strong> لا تقوم Zuzu: Bloomflight <strong>بجمع البيانات الشخصية أو مشاركتها أو بيعها أو إرسالها</strong>. تعمل النسخة الحالية دون اتصال، ولا تتضمن إعلانات أو تحليلات، وتحفظ التقدم والتفضيلات على الجهاز فقط.",
    futureAds: "<strong>تغيير مستقبلي محتمل:</strong> يجري النظر في إضافة الإعلانات إلى إصدار مستقبلي. لا توجد إعلانات نشطة حالياً. قبل أي إصدار يتضمن إعلانات، ستُحدّث هذه السياسة وإقرارات المتجر لتحديد المزودين ووصف الوصول إلى البيانات أو جمعها أو مشاركتها ومتطلبات الموافقة وحماية الأطفال.",
    sections: [
      ["1. حول التطبيق", "<p>Zuzu: Bloomflight لعبة أركيد بلمسة واحدة تقود فيها نحلة كرتونية ودودة عبر ست حدائق، وتطير وتحلق في المكان وتفتح الأزهار وتدير الرحيق وتجمع التعزيزات وتسعى إلى رقم قياسي.</p><p>هي لعبة لجمهور عام، موصى بها لمن هم <strong>بعمر 6 سنوات فأكثر</strong>، وليست مصممة حصراً للأطفال.</p>"],
      ["2. البيانات الشخصية", "<p><strong>لا يصل التطبيق إلى البيانات الشخصية أو الحساسة ولا يجمعها أو ينقلها أو يشاركها أو يبيعها</strong>. ولا يطلب الاسم أو البريد أو الهاتف أو الحساب أو تسجيل الدخول أو الموقع أو جهات الاتصال أو الصور أو الوسائط أو بيانات الدفع.</p>"],
      ["3. معلومات محفوظة على الجهاز فقط", "<p>يحفظ محلياً:</p><ul><li>أفضل نتيجة وعدد اللعبات والأزهار المفتوحة وأبعد حديقة؛</li><li>اللغة والصوت والموسيقى والاهتزاز الاختياري والوضع الساطع.</li></ul><p>عند التشغيل الأول قد تُقرأ لغة الجهاز محلياً. لا تغادر البيانات الجهاز ولا تتاح لـ BieMTech.</p>"],
      ["4. الاستخدام دون اتصال والأذونات", "<p>تعمل نسخة Android الحالية دون اتصال و<strong>لا تطلب الإنترنت</strong>. تطلب إذن الاهتزاز فقط للتغذية اللمسية الاختيارية. ولا تطلب الموقع أو الكاميرا أو الميكروفون أو جهات الاتصال أو التخزين الخارجي أو الإشعارات أو أذونات حساسة أخرى.</p>"],
      ["5. الأطفال والعمر", "<p>لا يوجد تسجيل أو دردشة أو ملف اجتماعي أو محتوى مستخدم أو إعلانات أو قمار أو مشتريات. يظهر فقط نحل ودود وزهور وعوائق خيالية واصطدام قصير غير صريح، بلا دماء أو عنف واقعي أو محتوى مخيف.</p><p>بسبب التوقيت وإدارة الموارد وسرعة الاستجابة توصي BieMTech بعمر <strong>6+</strong> وترى اللعبة مناسبة لجمهور واسع. تحدد الجهات الإقليمية التصنيفات الرسمية.</p>"],
      ["6. الإعلانات والتحليلات والجهات الخارجية", "<p>لا تحتوي النسخة الحالية على إعلانات أو أدوات خارجية للتحليل أو التتبع أو الأعطال أو الحسابات أو السحابة أو الميزات الاجتماعية أو الشراء. قد تُدرس الإعلانات لاحقاً، لكن الإقرارات والموافقة وحماية الأطفال ستُحدّث مسبقاً. وقد يعالج المتجر بياناته وفق سياسته.</p>"],
      ["7. الاحتفاظ والأمان والحذف", "<p>تبقى الإعدادات والإحصاءات على الجهاز حتى حذفها. امسح مساحة التطبيق في Android أو أزل التطبيق لحذف كل شيء. لا يلزم طلب حذف من الخادم لأنه لا تُرسل بيانات إلى BieMTech.</p>"],
      ["8. التغييرات والتواصل", "<p>قد نحدّث السياسة إذا تغير التطبيق أو ممارسات البيانات، وستُنشر المراجعة قبل الإصدار المعني.</p><p>للتواصل:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  hi: {
    dir: "ltr", back: "← BieMTech गोपनीयता नीतियाँ", subtitle: "गोपनीयता नीति", audience: "6+ वर्ष के लिए अनुशंसित · सामान्य दर्शकों का खेल", rights: "सर्वाधिकार सुरक्षित।", app: "ऐप", pkg: "पैकेज", updated: "अंतिम अपडेट", date: "3 अगस्त 2026",
    summary: "<strong>संक्षेप में:</strong> Zuzu: Bloomflight व्यक्तिगत डेटा <strong>एकत्र, साझा, बेचता या प्रसारित नहीं करता</strong>। वर्तमान संस्करण ऑफलाइन चलता है, इसमें विज्ञापन या एनालिटिक्स नहीं हैं और प्रगति व सेटिंग केवल डिवाइस पर रहती हैं।",
    futureAds: "<strong>संभावित भविष्य बदलाव:</strong> भविष्य के संस्करण में विज्ञापन जोड़ने पर विचार किया जा रहा है। वर्तमान संस्करण में विज्ञापन सक्रिय नहीं हैं। विज्ञापन वाले संस्करण से पहले इस नीति और स्टोर घोषणाओं में प्रदाता, डेटा पहुँच/संग्रह/साझाकरण, सहमति और बाल-सुरक्षा उपाय बताए जाएँगे।",
    sections: [
      ["1. ऐप के बारे में", "<p>Zuzu: Bloomflight एक-टच आर्केड गेम है जिसमें खिलाड़ी एक दोस्ताना कार्टून मधुमक्खी को छह बगीचों से ले जाता है, उड़ता और मँडराता है, फूल खिलाता है, नेक्टर सँभालता है, पावर-अप लेता है और रिकॉर्ड बनाता है।</p><p>यह सामान्य दर्शकों का गेम है, <strong>6 वर्ष और ऊपर</strong> के लिए अनुशंसित है और केवल बच्चों के लिए नहीं बनाया गया।</p>"],
      ["2. व्यक्तिगत डेटा", "<p>ऐप <strong>व्यक्तिगत या संवेदनशील डेटा तक पहुँच, संग्रह, प्रसारण, साझाकरण या बिक्री नहीं करता</strong>। यह नाम, ईमेल, फोन, खाता, लॉगिन, स्थान, संपर्क, फोटो, मीडिया या भुगतान जानकारी नहीं माँगता।</p>"],
      ["3. केवल डिवाइस पर जानकारी", "<p>स्थानीय रूप से सहेजा जाता है:</p><ul><li>सर्वश्रेष्ठ स्कोर, खेलों की संख्या, खिले फूल और सबसे दूर का बगीचा;</li><li>भाषा, ध्वनि, संगीत, वैकल्पिक कंपन और ब्राइट मोड।</li></ul><p>पहली बार डिवाइस भाषा स्थानीय रूप से पढ़ी जा सकती है। जानकारी डिवाइस से बाहर नहीं जाती और BieMTech को उपलब्ध नहीं होती।</p>"],
      ["4. ऑफलाइन उपयोग और अनुमतियाँ", "<p>वर्तमान Android संस्करण ऑफलाइन चलता है और <strong>इंटरनेट अनुमति नहीं माँगता</strong>। केवल वैकल्पिक हैप्टिक प्रतिक्रिया के लिए कंपन अनुमति है। स्थान, कैमरा, माइक्रोफोन, संपर्क, बाहरी स्टोरेज, नोटिफिकेशन या अन्य संवेदनशील अनुमति नहीं माँगी जाती।</p>"],
      ["5. बच्चे और आयु", "<p>पंजीकरण, चैट, सामाजिक प्रोफाइल, उपयोगकर्ता सामग्री, विज्ञापन, जुआ या खरीद नहीं है। दोस्ताना मधुमक्खी, फूल, काल्पनिक बाधाएँ और अंत में छोटी गैर-ग्राफिक टक्कर है; खून, वास्तविक हिंसा या डरावनी सामग्री नहीं।</p><p>समय, संसाधन और तेज प्रतिक्रिया के कारण BieMTech <strong>6+</strong> की अनुशंसा करता है और इसे व्यापक दर्शकों के लिए उचित मानता है। आधिकारिक रेटिंग क्षेत्रीय संस्थाएँ देती हैं।</p>"],
      ["6. विज्ञापन, एनालिटिक्स और तीसरे पक्ष", "<p>वर्तमान संस्करण में विज्ञापन या एनालिटिक्स, ट्रैकिंग, क्रैश, खाते, क्लाउड, सामाजिक सुविधा या खरीद के SDK नहीं हैं। भविष्य में विज्ञापन पर विचार हो सकता है, लेकिन घोषणाएँ, सहमति और बाल-सुरक्षा पहले अपडेट होंगी। स्टोर अपनी नीति के अनुसार डेटा संसाधित कर सकता है।</p>"],
      ["7. प्रतिधारण, सुरक्षा और हटाना", "<p>सेटिंग और आँकड़े हटाए जाने तक डिवाइस पर रहते हैं। Android में ऐप स्टोरेज साफ करें या ऐप अनइंस्टॉल करें। BieMTech सर्वर को डेटा नहीं जाता, इसलिए सर्वर अनुरोध आवश्यक नहीं।</p>"],
      ["8. बदलाव और संपर्क", "<p>ऐप या डेटा अभ्यास बदलने पर नीति अपडेट हो सकती है। संशोधन संबंधित रिलीज से पहले प्रकाशित होगा।</p><p>संपर्क:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  id: {
    dir: "ltr", back: "← Kebijakan Privasi BieMTech", subtitle: "Kebijakan Privasi", audience: "Disarankan untuk usia 6+ · Game untuk audiens umum", rights: "Hak cipta dilindungi.", app: "Aplikasi", pkg: "Paket", updated: "Terakhir diperbarui", date: "3 Agustus 2026",
    summary: "<strong>Singkatnya:</strong> Zuzu: Bloomflight <strong>tidak mengumpulkan, membagikan, menjual, atau mengirim</strong> data pribadi. Versi saat ini berjalan offline, tanpa iklan atau analitik, dan menyimpan progres serta preferensi hanya di perangkat.",
    futureAds: "<strong>Kemungkinan perubahan:</strong> Iklan sedang dipertimbangkan untuk versi mendatang. Iklan tidak aktif pada versi saat ini. Sebelum versi beriklan, kebijakan dan deklarasi toko akan diperbarui untuk menyebut penyedia, akses/pengumpulan/pembagian data, persetujuan, dan perlindungan anak.",
    sections: [
      ["1. Tentang aplikasi", "<p>Zuzu: Bloomflight adalah game arkade satu sentuhan: pemain memandu lebah kartun yang ramah melewati enam taman, terbang, melayang, memekarkan bunga, mengelola nektar, mengambil power-up, dan mengejar skor.</p><p>Game ini untuk audiens umum, disarankan bagi <strong>usia 6+</strong>, dan tidak dibuat khusus untuk anak-anak.</p>"],
      ["2. Data pribadi", "<p>Zuzu: Bloomflight <strong>tidak mengakses, mengumpulkan, mengirim, membagikan, atau menjual data pribadi atau sensitif</strong>. Game tidak meminta nama, email, telepon, akun, login, lokasi, kontak, foto, media, atau pembayaran.</p>"],
      ["3. Informasi hanya di perangkat", "<p>Yang disimpan lokal:</p><ul><li>skor terbaik, jumlah permainan, bunga mekar, dan taman terjauh;</li><li>bahasa, suara, musik, getar opsional, dan mode terang.</li></ul><p>Saat pertama dibuka, bahasa perangkat dapat dibaca secara lokal. Tidak ada informasi yang keluar atau tersedia bagi BieMTech.</p>"],
      ["4. Penggunaan offline dan izin", "<p>Versi Android saat ini berjalan offline dan <strong>tidak meminta Internet</strong>. Hanya izin getar untuk umpan balik haptik opsional. Tidak meminta lokasi, kamera, mikrofon, kontak, penyimpanan eksternal, notifikasi, atau izin sensitif lain.</p>"],
      ["5. Anak-anak dan usia", "<p>Tidak ada pendaftaran, obrolan, profil sosial, konten pengguna, iklan, perjudian, atau pembelian. Hanya ada lebah ramah, bunga, rintangan fantasi, dan benturan singkat tanpa grafis; tanpa darah, kekerasan realistis, atau konten menakutkan.</p><p>Karena membutuhkan waktu, pengelolaan sumber daya, dan reaksi cepat, BieMTech menyarankan <strong>usia 6+</strong> dan menilai game sesuai untuk audiens luas. Rating resmi ditentukan secara regional.</p>"],
      ["6. Iklan, analitik, dan pihak ketiga", "<p>Versi saat ini tidak memiliki iklan atau SDK pihak ketiga untuk analitik, pelacakan, laporan crash, akun, cloud, fitur sosial, atau pembelian. Iklan dapat dipertimbangkan kelak, tetapi deklarasi, persetujuan, dan perlindungan anak akan diperbarui lebih dahulu. Toko dapat memproses datanya sendiri sesuai kebijakan.</p>"],
      ["7. Penyimpanan, keamanan, dan penghapusan", "<p>Pengaturan dan statistik tetap di perangkat hingga dihapus. Bersihkan penyimpanan aplikasi di Android atau uninstall aplikasi. Karena data tidak dikirim ke server BieMTech, permintaan penghapusan server tidak diperlukan.</p>"],
      ["8. Perubahan dan kontak", "<p>Kebijakan dapat diperbarui jika aplikasi atau praktik data berubah. Revisi akan diterbitkan sebelum rilis terkait.</p><p>Kontak:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  zh: {
    dir: "ltr", back: "← BieMTech 隐私政策", subtitle: "隐私政策", audience: "建议6岁以上 · 普通受众游戏", rights: "版权所有。", app: "应用", pkg: "软件包", updated: "最后更新", date: "2026年8月3日",
    summary: "<strong>简而言之：</strong>Zuzu: Bloomflight <strong>不会收集、共享、出售或传输</strong>个人数据。当前版本完全离线，不含广告或分析，并仅在设备上保存进度和偏好。",
    futureAds: "<strong>未来可能的变化：</strong>未来版本正在考虑加入广告。当前版本尚未启用广告。发布含广告版本前，本政策和应用商店声明将更新，以说明服务商、数据访问/收集/共享以及所需的同意和儿童保护措施。",
    sections: [
      ["1. 关于本应用", "<p>Zuzu: Bloomflight 是一款单触街机游戏。玩家带领友好的卡通蜜蜂穿越六座花园，飞行、悬停、让花朵绽放、管理花蜜、收集道具并挑战高分。</p><p>本游戏面向普通受众，建议<strong>6岁以上</strong>游玩，并非专为儿童设计。</p>"],
      ["2. 个人数据", "<p>Zuzu: Bloomflight <strong>不会访问、收集、传输、共享或出售个人或敏感数据</strong>。不会要求姓名、电子邮件、电话、账号、登录、位置、联系人、照片、媒体或付款信息。</p>"],
      ["3. 仅存储在设备上的信息", "<p>游戏本地保存：</p><ul><li>最高分、游戏次数、绽放花朵数和到达的最远花园；</li><li>语言、音效、音乐、可选振动和明亮模式。</li></ul><p>首次启动时可能在本地读取设备语言。信息不会离开设备，BieMTech 也无法访问。</p>"],
      ["4. 离线使用与权限", "<p>当前 Android 版本完全离线，<strong>不申请互联网权限</strong>。只为可选触觉反馈申请振动权限。不会申请位置、相机、麦克风、联系人、外部存储、通知或其他敏感权限。</p>"],
      ["5. 儿童与年龄建议", "<p>没有注册、聊天、社交资料、用户内容、广告、赌博或购买。内容只有友好蜜蜂、花朵、幻想花园障碍和结束时短暂的非写实碰撞；没有血腥、写实暴力或恐怖内容。</p><p>由于需要时机、资源管理和快速反应，BieMTech 建议<strong>6岁以上</strong>，同时认为适合广泛受众。官方商店分级由地区机构另行确定。</p>"],
      ["6. 广告、分析与第三方", "<p>当前版本没有广告，也没有用于分析、跟踪、崩溃报告、账号、云端、社交或购买的第三方 SDK。未来可能考虑广告，但会先更新声明、同意要求和儿童保护措施。应用商店可能按其政策独立处理数据。</p>"],
      ["7. 保留、安全与删除", "<p>设置和统计保留在设备上直至删除。可在 Android 中清除应用存储或卸载应用。数据不会发送到 BieMTech 服务器，因此无需服务器删除请求。</p>"],
      ["8. 变更与联系", "<p>若应用或数据做法改变，我们可能更新本政策。修订版会在相关版本发布前公布。</p><p>联系：</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  }
};
