const WORD_WHEEL_POLICY = {
  en: {
    dir:"ltr", back:"← BieMTech Privacy Policies", subtitle:"Privacy Policy", audience:"Recommended for ages 12+ · General-audience game", rights:"All rights reserved.", app:"App", statusLabel:"Status", status:"In development", updated:"Last updated", date:"August 16, 2026",
    summary:"<strong>In short:</strong> Word Wheel does <strong>not collect, transmit, share, or sell personal data</strong>. The current build keeps game progress and preferences only on the device and contains no account, ads, analytics, or purchases.",
    future:"<strong>Before anything changes:</strong> If a future release adds online services, word reporting, advertising, analytics, or another third-party service, this policy and the relevant store disclosures will be updated before that feature is released.",
    sections:[
      ["1. About Word Wheel","<p>Word Wheel is a multilingual word puzzle. Players connect letters, fill crossword-style boards, find bonus words, earn tools, open geodes, and unlock collectible background cards.</p><p>BieMTech recommends the game for <strong>ages 12 and up</strong> because solving its vocabulary puzzles requires reading, reasoning, and word knowledge. It is a general-audience game and is not designed only for children.</p>"],
      ["2. Personal data","<p>The current build does <strong>not access, collect, transmit, share, or sell personal or sensitive data</strong>. It does not ask for a name, email address, phone number, account, login, location, contacts, photos, media, or payment information.</p>"],
      ["3. Information stored only on the device","<p>To remember the game between sessions, Word Wheel stores a local progress file containing:</p><ul><li>selected language and per-language level progress;</li><li>coins, bonus-word total, hints, picks, and reward-meter progress;</li><li>unlocked background cards, the selected background, and the levels where cards were earned;</li><li>sound preference and installed content-pack version.</li></ul><p>This information stays on the device and is not available to BieMTech.</p>"],
      ["4. Offline use and permissions","<p>The current build is designed to play offline and contains no active network request or cloud service. It does not require access to location, camera, microphone, contacts, photos, external storage, or other sensitive device data.</p>"],
      ["5. Age guidance and children","<p>Word Wheel has no registration, chat, public profile, user-generated content, targeted advertising, gambling, or purchases. BieMTech's <strong>12+</strong> recommendation reflects the reading and reasoning level of the puzzles; app stores may assign regional ratings separately.</p>"],
      ["6. Ads, analytics, and third parties","<p>The current build includes no third-party SDK for advertising, analytics, tracking, crash reporting, accounts, cloud saves, social features, or purchases. The app store may process its own download and device data separately under its own policy.</p>"],
      ["7. Retention, security, and deletion","<p>Local progress remains until it is removed on the device. To delete it, clear Word Wheel's app storage in device settings or uninstall the app. No server deletion request is needed because the current build sends no game data to BieMTech.</p>"],
      ["8. Changes and contact","<p>We may update this policy when the app or its data practices change. A revised policy will be published before the affected release.</p><p>Questions can be sent to BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  az: {
    dir:"ltr", back:"← BieMTech Məxfilik Siyasətləri", subtitle:"Məxfilik Siyasəti", audience:"12+ yaş üçün tövsiyə olunur · Ümumi auditoriya oyunu", rights:"Bütün hüquqlar qorunur.", app:"Tətbiq", statusLabel:"Status", status:"Hazırlanır", updated:"Son yenilənmə", date:"16 avqust 2026",
    summary:"<strong>Qısa məzmun:</strong> Word Wheel şəxsi məlumatları <strong>toplamır, ötürmür, paylaşmır və satmır</strong>. Cari versiya oyun irəliləyişini və seçimləri yalnız cihazda saxlayır; hesab, reklam, analitika və alış yoxdur.",
    future:"<strong>Dəyişiklikdən əvvəl:</strong> Gələcək versiyada onlayn xidmət, söz hesabatı, reklam, analitika və ya başqa üçüncü tərəf xidməti əlavə olunarsa, bu siyasət və müvafiq mağaza bəyannamələri həmin funksiya yayımlanmadan əvvəl yenilənəcək.",
    sections:[
      ["1. Word Wheel haqqında","<p>Word Wheel çoxdilli söz tapmacasıdır. Oyunçular hərfləri birləşdirir, krossvord tipli lövhələri doldurur, bonus sözlər tapır, alətlər qazanır, geodları açır və kolleksiya fon kartları əldə edir.</p><p>Söz tapmacaları oxu, məntiq və söz ehtiyatı tələb etdiyi üçün BieMTech oyunu <strong>12 yaş və yuxarı</strong> üçün tövsiyə edir. Oyun ümumi auditoriya üçündür və yalnız uşaqlar üçün hazırlanmayıb.</p>"],
      ["2. Şəxsi məlumatlar","<p>Cari versiya şəxsi və ya həssas məlumatlara <strong>çıxış etmir, onları toplamır, ötürmür, paylaşmır və satmır</strong>. Ad, e-poçt, telefon, hesab, giriş, məkan, kontakt, şəkil, media və ya ödəniş məlumatı istəmir.</p>"],
      ["3. Yalnız cihazda saxlanılan məlumatlar","<p>Oyun seanslar arasında irəliləyişi xatırlamaq üçün lokal faylda bunları saxlayır:</p><ul><li>seçilmiş dil və hər dil üzrə səviyyə irəliləyişi;</li><li>sikkələr, bonus söz sayı, ipucları, seçim alətləri və mükafat sayğacları;</li><li>açılmış fon kartları, seçilmiş fon və kartların qazanıldığı səviyyələr;</li><li>səs seçimi və kontent paketinin versiyası.</li></ul><p>Bu məlumatlar cihazda qalır və BieMTech üçün əlçatan deyil.</p>"],
      ["4. Oflayn istifadə və icazələr","<p>Cari versiya oflayn oynamaq üçün hazırlanıb və aktiv şəbəkə sorğusu və ya bulud xidməti ehtiva etmir. Məkan, kamera, mikrofon, kontaktlar, şəkillər, xarici yaddaş və digər həssas cihaz məlumatlarına çıxış tələb etmir.</p>"],
      ["5. Yaş tövsiyəsi və uşaqlar","<p>Word Wheel-də qeydiyyat, söhbət, açıq profil, istifadəçi kontenti, hədəfli reklam, qumar və alış yoxdur. BieMTech-in <strong>12+</strong> tövsiyəsi tapmacaların oxu və düşünmə səviyyəsini göstərir; mağazalar regional reytinqləri ayrıca təyin edə bilər.</p>"],
      ["6. Reklam, analitika və üçüncü tərəflər","<p>Cari versiyada reklam, analitika, izləmə, xəta hesabatı, hesab, bulud yaddaşı, sosial funksiya və ya alış üçün üçüncü tərəf SDK yoxdur. Tətbiq mağazası öz yükləmə və cihaz məlumatlarını öz siyasətinə əsasən ayrıca emal edə bilər.</p>"],
      ["7. Saxlama, təhlükəsizlik və silmə","<p>Lokal irəliləyiş cihazda silinənədək qalır. Silmək üçün cihaz ayarlarında Word Wheel yaddaşını təmizləyin və ya tətbiqi silin. Cari versiya BieMTech-ə oyun məlumatı göndərmədiyi üçün server silmə sorğusu lazım deyil.</p>"],
      ["8. Dəyişikliklər və əlaqə","<p>Tətbiq və ya məlumat təcrübələri dəyişərsə, siyasəti yeniləyə bilərik. Yeni siyasət aidiyyəti versiyadan əvvəl yayımlanacaq.</p><p>Suallar üçün BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  ru: {
    dir:"ltr", back:"← Политики конфиденциальности BieMTech", subtitle:"Политика конфиденциальности", audience:"Рекомендуется с 12 лет · Игра для широкой аудитории", rights:"Все права защищены.", app:"Приложение", statusLabel:"Статус", status:"В разработке", updated:"Последнее обновление", date:"16 августа 2026 г.",
    summary:"<strong>Кратко:</strong> Word Wheel <strong>не собирает, не передаёт, не распространяет и не продаёт персональные данные</strong>. Текущая версия хранит прогресс и настройки только на устройстве и не содержит аккаунтов, рекламы, аналитики или покупок.",
    future:"<strong>До любых изменений:</strong> Если будущая версия добавит онлайн-сервисы, отправку слов, рекламу, аналитику или иной сторонний сервис, эта политика и декларации магазина будут обновлены до выпуска такой функции.",
    sections:[
      ["1. О Word Wheel","<p>Word Wheel — многоязычная словесная головоломка. Игрок соединяет буквы, заполняет кроссворды, находит бонусные слова, получает инструменты, открывает жеоды и коллекционные фоновые карты.</p><p>BieMTech рекомендует игру <strong>с 12 лет</strong>, поскольку загадки требуют чтения, логики и словарного запаса. Игра предназначена для широкой аудитории, а не только для детей.</p>"],
      ["2. Персональные данные","<p>Текущая версия <strong>не получает доступ, не собирает, не передаёт, не распространяет и не продаёт</strong> персональные или конфиденциальные данные. Она не запрашивает имя, почту, телефон, аккаунт, вход, местоположение, контакты, фотографии, медиа или платёжную информацию.</p>"],
      ["3. Данные только на устройстве","<p>Локальный файл хранит:</p><ul><li>выбранный язык и прогресс по каждому языку;</li><li>монеты, бонусные слова, подсказки, инструменты и прогресс наград;</li><li>открытые фоновые карты, выбранный фон и уровни получения карт;</li><li>настройку звука и версию контент-пакета.</li></ul><p>Эти данные не покидают устройство и недоступны BieMTech.</p>"],
      ["4. Офлайн-работа и разрешения","<p>Текущая версия рассчитана на офлайн-игру и не содержит активных сетевых запросов или облачного сервиса. Ей не требуется доступ к местоположению, камере, микрофону, контактам, фотографиям, внешнему хранилищу или другим чувствительным данным устройства.</p>"],
      ["5. Возраст и дети","<p>В Word Wheel нет регистрации, чата, публичного профиля, пользовательского контента, целевой рекламы, азартных игр или покупок. Рекомендация <strong>12+</strong> отражает уровень чтения и мышления; магазины могут отдельно назначать региональные рейтинги.</p>"],
      ["6. Реклама, аналитика и третьи стороны","<p>В текущей версии нет сторонних SDK для рекламы, аналитики, отслеживания, отчётов об ошибках, аккаунтов, облака, социальных функций или покупок. Магазин приложений может отдельно обрабатывать данные о загрузке и устройстве по своей политике.</p>"],
      ["7. Хранение и удаление","<p>Локальный прогресс хранится до удаления на устройстве. Очистите данные Word Wheel в настройках или удалите приложение. Серверный запрос не нужен, поскольку текущая версия не отправляет игровые данные BieMTech.</p>"],
      ["8. Изменения и контакт","<p>Политика может обновляться при изменении приложения или работы с данными. Новая версия будет опубликована до соответствующего выпуска.</p><p>Вопросы можно направить BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  tr: {
    dir:"ltr", back:"← BieMTech Gizlilik Politikaları", subtitle:"Gizlilik Politikası", audience:"12 yaş ve üzeri için önerilir · Genel kitle oyunu", rights:"Tüm hakları saklıdır.", app:"Uygulama", statusLabel:"Durum", status:"Geliştiriliyor", updated:"Son güncelleme", date:"16 Ağustos 2026",
    summary:"<strong>Kısaca:</strong> Word Wheel kişisel verileri <strong>toplamaz, iletmez, paylaşmaz veya satmaz</strong>. Mevcut sürüm ilerleme ve tercihleri yalnızca cihazda tutar; hesap, reklam, analiz veya satın alma içermez.",
    future:"<strong>Herhangi bir değişiklikten önce:</strong> Gelecekte çevrimiçi hizmet, kelime raporlama, reklam, analiz veya başka bir üçüncü taraf hizmeti eklenirse bu politika ve mağaza beyanları özellik yayınlanmadan önce güncellenecektir.",
    sections:[
      ["1. Word Wheel hakkında","<p>Word Wheel çok dilli bir kelime bulmacasıdır. Oyuncular harfleri birleştirir, bulmaca tahtalarını doldurur, bonus kelimeler bulur, araçlar kazanır, jeotları açar ve koleksiyonluk arka plan kartları toplar.</p><p>Bulmacalar okuma, düşünme ve kelime bilgisi gerektirdiği için BieMTech oyunu <strong>12 yaş ve üzeri</strong> için önerir. Oyun genel kitleye yöneliktir ve yalnızca çocuklar için tasarlanmamıştır.</p>"],
      ["2. Kişisel veriler","<p>Mevcut sürüm kişisel veya hassas verilere <strong>erişmez; bunları toplamaz, iletmez, paylaşmaz veya satmaz</strong>. Ad, e-posta, telefon, hesap, giriş, konum, kişi, fotoğraf, medya veya ödeme bilgisi istemez.</p>"],
      ["3. Yalnızca cihazda saklanan bilgiler","<p>Yerel ilerleme dosyası şunları saklar:</p><ul><li>seçilen dil ve dil başına seviye ilerlemesi;</li><li>paralar, bonus kelimeler, ipuçları, araçlar ve ödül ilerlemesi;</li><li>açılan arka plan kartları, seçili arka plan ve kartların kazanıldığı seviyeler;</li><li>ses tercihi ve içerik paketi sürümü.</li></ul><p>Bu bilgiler cihazda kalır ve BieMTech tarafından erişilemez.</p>"],
      ["4. Çevrimdışı kullanım ve izinler","<p>Mevcut sürüm çevrimdışı oynamak için tasarlanmıştır ve etkin ağ isteği veya bulut hizmeti içermez. Konum, kamera, mikrofon, kişiler, fotoğraflar, harici depolama veya başka hassas cihaz verilerine erişim istemez.</p>"],
      ["5. Yaş rehberi ve çocuklar","<p>Word Wheel'de kayıt, sohbet, herkese açık profil, kullanıcı içeriği, hedefli reklam, kumar veya satın alma yoktur. <strong>12+</strong> önerisi bulmacaların okuma ve düşünme seviyesini belirtir; mağazalar bölgesel dereceleri ayrıca verebilir.</p>"],
      ["6. Reklam, analiz ve üçüncü taraflar","<p>Mevcut sürümde reklam, analiz, takip, hata raporu, hesap, bulut, sosyal özellik veya satın alma için üçüncü taraf SDK yoktur. Uygulama mağazası indirme ve cihaz verilerini kendi politikasına göre ayrı işleyebilir.</p>"],
      ["7. Saklama ve silme","<p>Yerel ilerleme cihazdan silinene kadar kalır. Cihaz ayarlarında Word Wheel depolamasını temizleyin veya uygulamayı kaldırın. Mevcut sürüm BieMTech'e oyun verisi göndermediği için sunucu silme isteği gerekmez.</p>"],
      ["8. Değişiklikler ve iletişim","<p>Uygulama veya veri uygulamaları değişirse politika güncellenebilir. Yeni politika ilgili sürümden önce yayınlanır.</p><p>Sorular için BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  de: {
    dir:"ltr", back:"← BieMTech-Datenschutzrichtlinien", subtitle:"Datenschutzrichtlinie", audience:"Empfohlen ab 12 Jahren · Spiel für ein allgemeines Publikum", rights:"Alle Rechte vorbehalten.", app:"App", statusLabel:"Status", status:"In Entwicklung", updated:"Zuletzt aktualisiert", date:"16. August 2026",
    summary:"<strong>Kurz gesagt:</strong> Word Wheel <strong>erfasst, überträgt, teilt oder verkauft keine personenbezogenen Daten</strong>. Der aktuelle Build speichert Fortschritt und Einstellungen nur auf dem Gerät und enthält kein Konto, keine Werbung, Analysen oder Käufe.",
    future:"<strong>Vor jeder Änderung:</strong> Falls eine künftige Version Onlinedienste, Wortmeldungen, Werbung, Analysen oder andere Drittanbieterdienste hinzufügt, werden diese Richtlinie und die Store-Angaben vor Veröffentlichung aktualisiert.",
    sections:[
      ["1. Über Word Wheel","<p>Word Wheel ist ein mehrsprachiges Worträtsel. Spielende verbinden Buchstaben, füllen Kreuzworträtsel, finden Bonuswörter, verdienen Werkzeuge, öffnen Geoden und sammeln Hintergrundkarten.</p><p>Da die Rätsel Lesen, Denken und Wortschatz erfordern, empfiehlt BieMTech das Spiel <strong>ab 12 Jahren</strong>. Es richtet sich an ein allgemeines Publikum und nicht nur an Kinder.</p>"],
      ["2. Personenbezogene Daten","<p>Der aktuelle Build <strong>greift nicht auf persönliche oder sensible Daten zu und erfasst, überträgt, teilt oder verkauft sie nicht</strong>. Name, E-Mail, Telefon, Konto, Anmeldung, Standort, Kontakte, Fotos, Medien und Zahlungsdaten werden nicht abgefragt.</p>"],
      ["3. Nur auf dem Gerät gespeicherte Daten","<p>Eine lokale Fortschrittsdatei speichert:</p><ul><li>Sprache und Fortschritt je Sprachpaket;</li><li>Münzen, Bonuswörter, Hinweise, Werkzeuge und Belohnungsfortschritt;</li><li>freigeschaltete Karten, ausgewählten Hintergrund und Karten-Level;</li><li>Soundeinstellung und Content-Pack-Version.</li></ul><p>Diese Daten bleiben auf dem Gerät und sind BieMTech nicht zugänglich.</p>"],
      ["4. Offline-Nutzung und Berechtigungen","<p>Der aktuelle Build ist für das Offline-Spiel ausgelegt und enthält keine aktive Netzwerkanfrage oder Cloud-Funktion. Er benötigt keinen Zugriff auf Standort, Kamera, Mikrofon, Kontakte, Fotos, externen Speicher oder andere sensible Gerätedaten.</p>"],
      ["5. Altersempfehlung und Kinder","<p>Word Wheel enthält keine Registrierung, Chats, öffentlichen Profile, Nutzerinhalte, zielgerichtete Werbung, Glücksspiele oder Käufe. Die Empfehlung <strong>12+</strong> bezieht sich auf Lese- und Denkniveau; Stores können regionale Altersfreigaben separat vergeben.</p>"],
      ["6. Werbung, Analysen und Dritte","<p>Im aktuellen Build gibt es keine Drittanbieter-SDKs für Werbung, Analysen, Tracking, Fehlerberichte, Konten, Cloud, soziale Funktionen oder Käufe. Der App-Store kann Download- und Gerätedaten nach seiner eigenen Richtlinie separat verarbeiten.</p>"],
      ["7. Aufbewahrung und Löschung","<p>Der lokale Fortschritt bleibt bis zur Löschung auf dem Gerät. Löschen Sie die Word-Wheel-App-Daten in den Geräteeinstellungen oder deinstallieren Sie die App. Eine Serveranfrage ist nicht nötig, da keine Spieldaten an BieMTech gesendet werden.</p>"],
      ["8. Änderungen und Kontakt","<p>Wir können diese Richtlinie bei Änderungen an App oder Datenpraxis aktualisieren. Die neue Fassung erscheint vor der betroffenen Version.</p><p>Fragen an BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  fr: {
    dir:"ltr", back:"← Politiques de confidentialité BieMTech", subtitle:"Politique de confidentialité", audience:"Recommandé dès 12 ans · Jeu tout public", rights:"Tous droits réservés.", app:"Application", statusLabel:"Statut", status:"En développement", updated:"Dernière mise à jour", date:"16 août 2026",
    summary:"<strong>En bref :</strong> Word Wheel <strong>ne collecte, ne transmet, ne partage et ne vend aucune donnée personnelle</strong>. La version actuelle conserve la progression et les préférences uniquement sur l'appareil, sans compte, publicité, analyse ni achat.",
    future:"<strong>Avant tout changement :</strong> Si une future version ajoute des services en ligne, le signalement de mots, de la publicité, des analyses ou un autre service tiers, cette politique et les déclarations du store seront mises à jour avant sa publication.",
    sections:[
      ["1. À propos de Word Wheel","<p>Word Wheel est un jeu de mots multilingue. Les joueurs relient des lettres, remplissent des grilles, trouvent des mots bonus, gagnent des outils, ouvrent des géodes et collectionnent des cartes d'arrière-plan.</p><p>Comme les énigmes demandent lecture, réflexion et vocabulaire, BieMTech recommande le jeu <strong>dès 12 ans</strong>. Il s'adresse au grand public et n'est pas conçu uniquement pour les enfants.</p>"],
      ["2. Données personnelles","<p>La version actuelle <strong>n'accède pas aux données personnelles ou sensibles et ne les collecte, transmet, partage ou vend pas</strong>. Elle ne demande aucun nom, e-mail, téléphone, compte, connexion, emplacement, contact, photo, média ou paiement.</p>"],
      ["3. Informations stockées uniquement sur l'appareil","<p>Un fichier local conserve :</p><ul><li>la langue et la progression par langue ;</li><li>les pièces, mots bonus, indices, outils et jauges de récompense ;</li><li>les cartes débloquées, le fond choisi et les niveaux d'obtention ;</li><li>le réglage du son et la version du pack.</li></ul><p>Ces informations restent sur l'appareil et ne sont pas accessibles à BieMTech.</p>"],
      ["4. Utilisation hors ligne et autorisations","<p>La version actuelle est conçue pour jouer hors ligne et ne contient aucune requête réseau active ni service cloud. Elle ne demande pas l'accès à la position, caméra, microphone, contacts, photos, stockage externe ou autre donnée sensible.</p>"],
      ["5. Âge et enfants","<p>Word Wheel ne propose ni inscription, chat, profil public, contenu utilisateur, publicité ciblée, jeu d'argent ou achat. La recommandation <strong>12+</strong> reflète le niveau de lecture et de réflexion ; les stores peuvent attribuer leurs propres classifications régionales.</p>"],
      ["6. Publicité, analyses et tiers","<p>La version actuelle n'intègre aucun SDK tiers de publicité, analyse, suivi, rapport d'erreur, compte, cloud, fonction sociale ou achat. Le store peut traiter séparément ses données de téléchargement et d'appareil selon sa politique.</p>"],
      ["7. Conservation et suppression","<p>La progression locale reste jusqu'à sa suppression sur l'appareil. Effacez les données de Word Wheel dans les réglages ou désinstallez l'application. Aucune demande serveur n'est nécessaire car aucune donnée de jeu n'est envoyée à BieMTech.</p>"],
      ["8. Modifications et contact","<p>Cette politique peut évoluer si l'application ou ses pratiques changent. La nouvelle version sera publiée avant la sortie concernée.</p><p>Questions pour BieMTech :</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  es: {
    dir:"ltr", back:"← Políticas de privacidad de BieMTech", subtitle:"Política de privacidad", audience:"Recomendado para mayores de 12 · Juego para público general", rights:"Todos los derechos reservados.", app:"Aplicación", statusLabel:"Estado", status:"En desarrollo", updated:"Última actualización", date:"16 de agosto de 2026",
    summary:"<strong>En resumen:</strong> Word Wheel <strong>no recopila, transmite, comparte ni vende datos personales</strong>. La versión actual guarda el progreso y las preferencias solo en el dispositivo y no contiene cuentas, anuncios, analíticas ni compras.",
    future:"<strong>Antes de cualquier cambio:</strong> Si una versión futura añade servicios en línea, informes de palabras, publicidad, analíticas u otro servicio externo, esta política y las declaraciones de la tienda se actualizarán antes de publicar la función.",
    sections:[
      ["1. Acerca de Word Wheel","<p>Word Wheel es un puzle de palabras multilingüe. Los jugadores conectan letras, completan crucigramas, encuentran palabras extra, ganan herramientas, abren geodas y coleccionan tarjetas de fondo.</p><p>Como los puzles requieren lectura, razonamiento y vocabulario, BieMTech recomienda el juego para <strong>mayores de 12 años</strong>. Es para público general y no está diseñado solo para niños.</p>"],
      ["2. Datos personales","<p>La versión actual <strong>no accede, recopila, transmite, comparte ni vende datos personales o sensibles</strong>. No solicita nombre, correo, teléfono, cuenta, inicio de sesión, ubicación, contactos, fotos, archivos multimedia ni pagos.</p>"],
      ["3. Información almacenada solo en el dispositivo","<p>Un archivo local guarda:</p><ul><li>idioma y progreso por idioma;</li><li>monedas, palabras extra, pistas, herramientas y progreso de premios;</li><li>fondos desbloqueados, fondo seleccionado y niveles donde se obtuvieron;</li><li>preferencia de sonido y versión del paquete.</li></ul><p>Estos datos permanecen en el dispositivo y BieMTech no puede acceder a ellos.</p>"],
      ["4. Uso sin conexión y permisos","<p>La versión actual está diseñada para jugar sin conexión y no contiene solicitudes de red activas ni servicios en la nube. No requiere acceso a ubicación, cámara, micrófono, contactos, fotos, almacenamiento externo u otros datos sensibles.</p>"],
      ["5. Edad y menores","<p>Word Wheel no incluye registro, chat, perfil público, contenido de usuario, publicidad dirigida, apuestas ni compras. La recomendación <strong>12+</strong> refleja el nivel de lectura y razonamiento; las tiendas pueden asignar clasificaciones regionales por separado.</p>"],
      ["6. Anuncios, analíticas y terceros","<p>La versión actual no incluye SDK de terceros para publicidad, analíticas, seguimiento, fallos, cuentas, nube, funciones sociales o compras. La tienda puede tratar por separado datos de descarga y dispositivo bajo su propia política.</p>"],
      ["7. Conservación y eliminación","<p>El progreso local permanece hasta que se elimina del dispositivo. Borra los datos de Word Wheel en los ajustes o desinstala la aplicación. No hace falta una solicitud al servidor porque no se envían datos de juego a BieMTech.</p>"],
      ["8. Cambios y contacto","<p>Podemos actualizar esta política si cambian la aplicación o sus prácticas. La nueva política se publicará antes de la versión afectada.</p><p>Preguntas para BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  pt: {
    dir:"ltr", back:"← Políticas de Privacidade da BieMTech", subtitle:"Política de Privacidade", audience:"Recomendado para maiores de 12 · Jogo para público geral", rights:"Todos os direitos reservados.", app:"Aplicativo", statusLabel:"Status", status:"Em desenvolvimento", updated:"Última atualização", date:"16 de agosto de 2026",
    summary:"<strong>Em resumo:</strong> Word Wheel <strong>não coleta, transmite, compartilha ou vende dados pessoais</strong>. A versão atual guarda progresso e preferências apenas no aparelho e não contém conta, anúncios, análises ou compras.",
    future:"<strong>Antes de qualquer mudança:</strong> Se uma versão futura adicionar serviços online, relato de palavras, publicidade, análises ou outro serviço de terceiros, esta política e as declarações da loja serão atualizadas antes do lançamento.",
    sections:[
      ["1. Sobre o Word Wheel","<p>Word Wheel é um jogo de palavras multilíngue. Os jogadores ligam letras, preenchem palavras cruzadas, encontram palavras bônus, ganham ferramentas, abrem geodos e colecionam cartões de fundo.</p><p>Como os desafios exigem leitura, raciocínio e vocabulário, a BieMTech recomenda o jogo para <strong>maiores de 12 anos</strong>. Ele é para o público geral e não foi criado apenas para crianças.</p>"],
      ["2. Dados pessoais","<p>A versão atual <strong>não acessa, coleta, transmite, compartilha ou vende dados pessoais ou sensíveis</strong>. Não pede nome, e-mail, telefone, conta, login, localização, contatos, fotos, mídia ou pagamento.</p>"],
      ["3. Informações armazenadas apenas no aparelho","<p>Um arquivo local guarda:</p><ul><li>idioma e progresso por idioma;</li><li>moedas, palavras bônus, dicas, ferramentas e progresso de recompensas;</li><li>fundos desbloqueados, fundo escolhido e níveis em que foram obtidos;</li><li>preferência de som e versão do pacote.</li></ul><p>Esses dados ficam no aparelho e não são acessíveis à BieMTech.</p>"],
      ["4. Uso offline e permissões","<p>A versão atual foi criada para jogar offline e não contém solicitação de rede ativa nem serviço de nuvem. Não exige acesso a localização, câmera, microfone, contatos, fotos, armazenamento externo ou outros dados sensíveis.</p>"],
      ["5. Idade e crianças","<p>Word Wheel não possui cadastro, chat, perfil público, conteúdo de usuário, publicidade direcionada, apostas ou compras. A recomendação <strong>12+</strong> reflete o nível de leitura e raciocínio; as lojas podem atribuir classificações regionais separadamente.</p>"],
      ["6. Anúncios, análises e terceiros","<p>A versão atual não inclui SDK de terceiros para publicidade, análises, rastreamento, falhas, contas, nuvem, recursos sociais ou compras. A loja pode tratar separadamente dados de download e aparelho conforme sua política.</p>"],
      ["7. Retenção e exclusão","<p>O progresso local permanece até ser apagado no aparelho. Limpe os dados do Word Wheel nas configurações ou desinstale o aplicativo. Não é preciso pedir exclusão ao servidor porque nenhum dado do jogo é enviado à BieMTech.</p>"],
      ["8. Mudanças e contato","<p>Podemos atualizar esta política se o aplicativo ou suas práticas mudarem. A nova política será publicada antes da versão afetada.</p><p>Perguntas para a BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  it: {
    dir:"ltr", back:"← Informative privacy BieMTech", subtitle:"Informativa sulla privacy", audience:"Consigliato dai 12 anni · Gioco per il pubblico generale", rights:"Tutti i diritti riservati.", app:"App", statusLabel:"Stato", status:"In sviluppo", updated:"Ultimo aggiornamento", date:"16 agosto 2026",
    summary:"<strong>In breve:</strong> Word Wheel <strong>non raccoglie, trasmette, condivide o vende dati personali</strong>. La versione attuale conserva progressi e preferenze solo sul dispositivo e non contiene account, annunci, analisi o acquisti.",
    future:"<strong>Prima di ogni modifica:</strong> Se una versione futura aggiungerà servizi online, segnalazione di parole, pubblicità, analisi o altri servizi di terze parti, questa informativa e le dichiarazioni dello store saranno aggiornate prima del rilascio.",
    sections:[
      ["1. Informazioni su Word Wheel","<p>Word Wheel è un rompicapo di parole multilingue. I giocatori collegano lettere, completano schemi, trovano parole bonus, ottengono strumenti, aprono geodi e collezionano carte sfondo.</p><p>Poiché i rompicapi richiedono lettura, ragionamento e vocabolario, BieMTech consiglia il gioco <strong>dai 12 anni</strong>. È rivolto al pubblico generale e non solo ai bambini.</p>"],
      ["2. Dati personali","<p>La versione attuale <strong>non accede, raccoglie, trasmette, condivide o vende dati personali o sensibili</strong>. Non richiede nome, e-mail, telefono, account, accesso, posizione, contatti, foto, media o pagamenti.</p>"],
      ["3. Informazioni conservate solo sul dispositivo","<p>Un file locale salva:</p><ul><li>lingua e avanzamento per lingua;</li><li>monete, parole bonus, suggerimenti, strumenti e premi;</li><li>sfondi sbloccati, sfondo scelto e livelli di ottenimento;</li><li>preferenza audio e versione del pacchetto.</li></ul><p>Questi dati restano sul dispositivo e non sono accessibili a BieMTech.</p>"],
      ["4. Uso offline e autorizzazioni","<p>La versione attuale è pensata per giocare offline e non contiene richieste di rete attive né servizi cloud. Non richiede posizione, fotocamera, microfono, contatti, foto, memoria esterna o altri dati sensibili.</p>"],
      ["5. Età e minori","<p>Word Wheel non include registrazione, chat, profili pubblici, contenuti utente, pubblicità mirata, gioco d'azzardo o acquisti. La raccomandazione <strong>12+</strong> riflette il livello di lettura e ragionamento; gli store possono assegnare valutazioni regionali separate.</p>"],
      ["6. Annunci, analisi e terze parti","<p>La versione attuale non include SDK di terze parti per pubblicità, analisi, tracciamento, crash, account, cloud, funzioni social o acquisti. Lo store può trattare separatamente dati di download e dispositivo secondo la propria politica.</p>"],
      ["7. Conservazione ed eliminazione","<p>I progressi locali restano finché non vengono eliminati dal dispositivo. Cancella i dati di Word Wheel nelle impostazioni o disinstalla l'app. Non serve una richiesta al server perché nessun dato di gioco viene inviato a BieMTech.</p>"],
      ["8. Modifiche e contatti","<p>Possiamo aggiornare l'informativa se cambiano l'app o le sue pratiche. La nuova versione sarà pubblicata prima del rilascio interessato.</p><p>Domande a BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  ar: {
    dir:"rtl", back:"سياسات خصوصية BieMTech ←", subtitle:"سياسة الخصوصية", audience:"موصى به لعمر 12+ · لعبة للجمهور العام", rights:"جميع الحقوق محفوظة.", app:"التطبيق", statusLabel:"الحالة", status:"قيد التطوير", updated:"آخر تحديث", date:"16 أغسطس 2026",
    summary:"<strong>باختصار:</strong> لا تجمع Word Wheel البيانات الشخصية ولا تنقلها أو تشاركها أو تبيعها. يحفظ الإصدار الحالي التقدم والتفضيلات على الجهاز فقط، ولا يتضمن حساباً أو إعلانات أو تحليلات أو مشتريات.",
    future:"<strong>قبل أي تغيير:</strong> إذا أضاف إصدار مستقبلي خدمات عبر الإنترنت أو إرسال الكلمات أو الإعلانات أو التحليلات أو خدمة خارجية أخرى، فسيتم تحديث هذه السياسة وإفصاحات المتجر قبل إصدار الميزة.",
    sections:[
      ["1. حول Word Wheel","<p>Word Wheel لعبة ألغاز كلمات متعددة اللغات. يصل اللاعبون الحروف ويملؤون لوحات الكلمات ويجدون كلمات إضافية ويكسبون أدوات ويفتحون الجيود ويجمعون بطاقات الخلفيات.</p><p>لأن الألغاز تتطلب القراءة والتفكير والمعرفة اللغوية، توصي BieMTech باللعبة <strong>لعمر 12 سنة فأكثر</strong>. وهي موجهة للجمهور العام وليست للأطفال فقط.</p>"],
      ["2. البيانات الشخصية","<p>لا يصل الإصدار الحالي إلى البيانات الشخصية أو الحساسة ولا <strong>يجمعها أو ينقلها أو يشاركها أو يبيعها</strong>. ولا يطلب الاسم أو البريد أو الهاتف أو الحساب أو تسجيل الدخول أو الموقع أو جهات الاتصال أو الصور أو الوسائط أو الدفع.</p>"],
      ["3. معلومات محفوظة على الجهاز فقط","<p>يحفظ ملف محلي:</p><ul><li>اللغة والتقدم لكل لغة؛</li><li>العملات والكلمات الإضافية والتلميحات والأدوات والمكافآت؛</li><li>الخلفيات المفتوحة والخلفية المختارة ومستويات الحصول عليها؛</li><li>تفضيل الصوت وإصدار حزمة المحتوى.</li></ul><p>تبقى هذه البيانات على الجهاز ولا تستطيع BieMTech الوصول إليها.</p>"],
      ["4. اللعب دون اتصال والأذونات","<p>صُمم الإصدار الحالي للعب دون اتصال ولا يحتوي على طلب شبكة نشط أو خدمة سحابية. ولا يحتاج إلى الموقع أو الكاميرا أو الميكروفون أو جهات الاتصال أو الصور أو التخزين الخارجي أو بيانات حساسة أخرى.</p>"],
      ["5. العمر والأطفال","<p>لا تحتوي Word Wheel على تسجيل أو دردشة أو ملف عام أو محتوى مستخدم أو إعلان موجّه أو مقامرة أو شراء. تعكس توصية <strong>12+</strong> مستوى القراءة والتفكير، وقد تعيّن المتاجر تصنيفات إقليمية بشكل منفصل.</p>"],
      ["6. الإعلانات والتحليلات والجهات الخارجية","<p>لا يتضمن الإصدار الحالي SDK خارجياً للإعلانات أو التحليلات أو التتبع أو تقارير الأعطال أو الحسابات أو السحابة أو الميزات الاجتماعية أو الشراء. قد يعالج المتجر بيانات التنزيل والجهاز بشكل منفصل وفق سياسته.</p>"],
      ["7. الاحتفاظ والحذف","<p>يبقى التقدم المحلي حتى حذفه من الجهاز. امسح بيانات Word Wheel من الإعدادات أو أزل التطبيق. لا يلزم طلب حذف من خادم لأن الإصدار الحالي لا يرسل بيانات اللعب إلى BieMTech.</p>"],
      ["8. التغييرات والتواصل","<p>قد نحدّث السياسة عند تغير التطبيق أو ممارساته. ستنشر السياسة الجديدة قبل الإصدار المتأثر.</p><p>للاستفسار تواصل مع BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  zh: {
    dir:"ltr", back:"← BieMTech 隐私政策", subtitle:"隐私政策", audience:"建议12岁以上 · 面向普通用户", rights:"保留所有权利。", app:"应用", statusLabel:"状态", status:"开发中", updated:"最后更新", date:"2026年8月16日",
    summary:"<strong>简而言之：</strong>Word Wheel <strong>不会收集、传输、共享或出售个人数据</strong>。当前版本仅在设备上保存进度和偏好，不含账户、广告、分析或购买。",
    future:"<strong>任何变化之前：</strong>如果未来版本加入在线服务、单词报告、广告、分析或其他第三方服务，我们会在该功能发布前更新本政策和相关商店披露。",
    sections:[
      ["1. 关于 Word Wheel","<p>Word Wheel 是一款多语言文字谜题。玩家连接字母、填写纵横字谜、寻找奖励词、获得工具、打开晶洞并收藏背景卡。</p><p>由于谜题需要阅读、推理和词汇知识，BieMTech 建议 <strong>12岁以上</strong>游玩。本游戏面向普通用户，并非仅为儿童设计。</p>"],
      ["2. 个人数据","<p>当前版本<strong>不会访问、收集、传输、共享或出售个人或敏感数据</strong>。它不会要求姓名、邮箱、电话、账户、登录、位置、联系人、照片、媒体或付款信息。</p>"],
      ["3. 仅存储在设备上的信息","<p>本地进度文件保存：</p><ul><li>所选语言及各语言进度；</li><li>金币、奖励词、提示、工具和奖励进度；</li><li>已解锁背景、当前背景和获得卡片的关卡；</li><li>声音偏好和内容包版本。</li></ul><p>这些信息保留在设备上，BieMTech 无法访问。</p>"],
      ["4. 离线使用与权限","<p>当前版本为离线游玩而设计，不含活动网络请求或云服务。它不需要访问位置、相机、麦克风、联系人、照片、外部存储或其他敏感设备数据。</p>"],
      ["5. 年龄指导与儿童","<p>Word Wheel 没有注册、聊天、公开资料、用户内容、定向广告、赌博或购买。<strong>12+</strong>建议反映谜题的阅读和推理水平；应用商店可另行给出地区评级。</p>"],
      ["6. 广告、分析和第三方","<p>当前版本不含用于广告、分析、跟踪、崩溃报告、账户、云端、社交功能或购买的第三方 SDK。应用商店可按其政策单独处理下载和设备数据。</p>"],
      ["7. 保留与删除","<p>本地进度会保留至从设备删除。在设置中清除 Word Wheel 数据或卸载应用即可删除。当前版本不会向 BieMTech 发送游戏数据，因此无需服务器删除请求。</p>"],
      ["8. 变更与联系","<p>应用或数据做法发生变化时，我们可能更新本政策。新政策将在受影响版本之前发布。</p><p>问题请联系 BieMTech：</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  ja: {
    dir:"ltr", back:"← BieMTech プライバシーポリシー", subtitle:"プライバシーポリシー", audience:"12歳以上推奨 · 一般向けゲーム", rights:"無断転載を禁じます。", app:"アプリ", statusLabel:"状態", status:"開発中", updated:"最終更新", date:"2026年8月16日",
    summary:"<strong>要約：</strong>Word Wheel は個人データを<strong>収集、送信、共有、販売しません</strong>。現在のバージョンは進行状況と設定を端末内だけに保存し、アカウント、広告、解析、購入を含みません。",
    future:"<strong>変更前のお知らせ：</strong>将来オンラインサービス、単語報告、広告、解析、その他の第三者サービスを追加する場合、このポリシーとストアの開示を機能公開前に更新します。",
    sections:[
      ["1. Word Wheel について","<p>Word Wheel は多言語ワードパズルです。文字をつなぎ、クロスワード盤を埋め、ボーナスワードを見つけ、道具を獲得し、ジオードや背景カードを開きます。</p><p>パズルには読解、推理、語彙力が必要なため、BieMTech は<strong>12歳以上</strong>を推奨しています。一般向けのゲームで、子ども専用ではありません。</p>"],
      ["2. 個人データ","<p>現在のバージョンは個人情報や機微データに<strong>アクセスせず、収集、送信、共有、販売もしません</strong>。氏名、メール、電話、アカウント、ログイン、位置情報、連絡先、写真、メディア、支払い情報を求めません。</p>"],
      ["3. 端末内だけに保存される情報","<p>ローカル進行ファイルには次を保存します。</p><ul><li>選択言語と言語ごとの進行状況</li><li>コイン、ボーナスワード、ヒント、道具、報酬の進行</li><li>開放した背景、選択中の背景、カード獲得レベル</li><li>サウンド設定とコンテンツパック版</li></ul><p>これらは端末内に留まり、BieMTech はアクセスできません。</p>"],
      ["4. オフライン利用と権限","<p>現在のバージョンはオフラインプレイ用で、実行中のネットワーク要求やクラウドサービスはありません。位置情報、カメラ、マイク、連絡先、写真、外部ストレージなどの機微データへのアクセスを必要としません。</p>"],
      ["5. 年齢案内と子ども","<p>Word Wheel には登録、チャット、公開プロフィール、ユーザー投稿、ターゲット広告、ギャンブル、購入がありません。<strong>12+</strong>推奨は読解・推理レベルを示し、ストアは地域別レーティングを別途設定できます。</p>"],
      ["6. 広告、解析、第三者","<p>現在のバージョンには広告、解析、追跡、クラッシュ報告、アカウント、クラウド、ソーシャル機能、購入の第三者 SDK はありません。ストアは独自ポリシーに従ってダウンロードや端末データを別途処理する場合があります。</p>"],
      ["7. 保持と削除","<p>ローカル進行状況は端末で削除されるまで残ります。設定で Word Wheel のデータを消去するか、アプリをアンインストールしてください。現在の版はゲームデータを BieMTech に送らないため、サーバー削除依頼は不要です。</p>"],
      ["8. 変更と連絡先","<p>アプリやデータ取扱いが変わる場合、本ポリシーを更新することがあります。改訂版は対象リリース前に公開します。</p><p>BieMTech へのお問い合わせ：</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  }
};
