const WORD_WHEEL_POLICY = {
  en: {
    dir:"ltr", back:"← BieMTech Privacy Policies", subtitle:"Privacy Policy", audience:"Recommended for ages 12+ · General-audience game", rights:"All rights reserved.", app:"App", statusLabel:"Status", status:"Live on Google Play", updated:"Last updated", date:"September 9, 2026",
    summary:"<strong>In short:</strong> Word Wheel keeps core progress and preferences on your device and does not sell personal data. Core play works offline. Optional Google Play Games sign-in and the XP leaderboard use Google's service only when you choose those features. The game contains no ads, analytics, or purchases.",
    future:"<strong>Before anything changes:</strong> If a future release adds online services, word reporting, advertising, analytics, or another third-party service, this policy and the relevant store disclosures will be updated before that feature is released.",
    sections:[
      ["1. About Word Wheel","<p>Word Wheel is a multilingual word puzzle. Players connect letters, fill crossword-style boards, find bonus words, earn tools, open geodes, and unlock collectible background cards.</p><p>BieMTech recommends the game for <strong>ages 12 and up</strong> because solving its vocabulary puzzles requires reading, reasoning, and word knowledge. It is a general-audience game and is not designed only for children.</p>"],
      ["2. Personal data and Google Play Games","<p>Word Wheel itself does <strong>not ask for or collect</strong> your name, email address, phone number, location, contacts, photos, media, or payment information.</p><p>If you choose Google Play Games sign-in or the XP leaderboard, Google may process your Play Games account, player identifier, profile, and score data under Google's own privacy policy. The game submits XP and reads leaderboard entries only for that optional feature.</p>"],
      ["3. Information stored only on the device","<p>To remember the game between sessions, Word Wheel stores a local progress file containing:</p><ul><li>selected language and per-language level progress;</li><li>coins, bonus-word total, hints, picks, and reward-meter progress;</li><li>unlocked background cards, the selected background, and the levels where cards were earned;</li><li>sound preference and installed content-pack version.</li></ul><p>This information stays on the device and is not available to BieMTech.</p>"],
      ["4. Offline use, connectivity, and permissions","<p>Core gameplay works offline. Internet access is used only for optional Google Play Games sign-in and the XP leaderboard. The game does not request location, camera, microphone, contacts, photos, external storage, or other sensitive device data.</p>"],
      ["5. Age guidance and children","<p>Word Wheel has no registration, chat, public profile, user-generated content, targeted advertising, gambling, or purchases. BieMTech's <strong>12+</strong> recommendation reflects the reading and reasoning level of the puzzles; app stores may assign regional ratings separately.</p>"],
      ["6. Ads, analytics, and third parties","<p>The current version contains no ads and no third-party analytics, tracking, crash-reporting, cloud-save, social-network, or purchase SDKs. Google Play Games is the only optional online integration and is governed by Google's policies. Google Play may also process store and device data separately from the game.</p>"],
      ["7. Retention, security, and deletion","<p>Local progress remains until it is removed on the device. To delete it, clear Word Wheel's app storage in device settings or uninstall the app. No server deletion request is needed because the current build sends no game data to BieMTech.</p>"],
      ["8. Changes and contact","<p>We may update this policy when the app or its data practices change. A revised policy will be published before the affected release.</p><p>Questions can be sent to BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  az: {
    dir:"ltr", back:"← BieMTech Məxfilik Siyasətləri", subtitle:"Məxfilik Siyasəti", audience:"12+ yaş üçün tövsiyə olunur · Ümumi auditoriya oyunu", rights:"Bütün hüquqlar qorunur.", app:"Tətbiq", statusLabel:"Status", status:"Google Play-də yayımdadır", updated:"Son yenilənmə", date:"9 sentyabr 2026",
    summary:"<strong>Qısa məzmun:</strong> Word Wheel əsas irəliləyiş və seçimləri cihazınızda saxlayır və şəxsi məlumatları satmır. Əsas oyun oflayn işləyir. İstəyə bağlı Google Play Games girişi və XP lider cədvəli yalnız siz bu funksiyaları seçəndə Google xidmətindən istifadə edir. Oyunda reklam, analitika və alış yoxdur.",
    future:"<strong>Dəyişiklikdən əvvəl:</strong> Gələcək versiyada onlayn xidmət, söz hesabatı, reklam, analitika və ya başqa üçüncü tərəf xidməti əlavə olunarsa, bu siyasət və müvafiq mağaza bəyannamələri həmin funksiya yayımlanmadan əvvəl yenilənəcək.",
    sections:[
      ["1. Word Wheel haqqında","<p>Word Wheel çoxdilli söz tapmacasıdır. Oyunçular hərfləri birləşdirir, krossvord tipli lövhələri doldurur, bonus sözlər tapır, alətlər qazanır, geodları açır və kolleksiya fon kartları əldə edir.</p><p>Söz tapmacaları oxu, məntiq və söz ehtiyatı tələb etdiyi üçün BieMTech oyunu <strong>12 yaş və yuxarı</strong> üçün tövsiyə edir. Oyun ümumi auditoriya üçündür və yalnız uşaqlar üçün hazırlanmayıb.</p>"],
      ["2. Şəxsi məlumatlar və Google Play Games","<p>Word Wheel özü ad, e-poçt, telefon, məkan, kontakt, şəkil, media və ya ödəniş məlumatınızı <strong>istəmir və toplamır</strong>.</p><p>Google Play Games girişini və ya XP lider cədvəlini seçsəniz, Google öz məxfilik siyasətinə əsasən Play Games hesabınızı, oyunçu identifikatorunuzu, profilinizi və xal məlumatınızı emal edə bilər. Oyun yalnız bu istəyə bağlı funksiya üçün XP göndərir və lider cədvəlini oxuyur.</p>"],
      ["3. Yalnız cihazda saxlanılan məlumatlar","<p>Oyun seanslar arasında irəliləyişi xatırlamaq üçün lokal faylda bunları saxlayır:</p><ul><li>seçilmiş dil və hər dil üzrə səviyyə irəliləyişi;</li><li>sikkələr, bonus söz sayı, ipucları, seçim alətləri və mükafat sayğacları;</li><li>açılmış fon kartları, seçilmiş fon və kartların qazanıldığı səviyyələr;</li><li>səs seçimi və kontent paketinin versiyası.</li></ul><p>Bu məlumatlar cihazda qalır və BieMTech üçün əlçatan deyil.</p>"],
      ["4. Oflayn istifadə, bağlantı və icazələr","<p>Əsas oyun oflayn işləyir. İnternet yalnız istəyə bağlı Google Play Games girişi və XP lider cədvəli üçün istifadə olunur. Oyun məkan, kamera, mikrofon, kontakt, şəkil, xarici yaddaş və digər həssas cihaz məlumatlarına giriş istəmir.</p>"],
      ["5. Yaş tövsiyəsi və uşaqlar","<p>Word Wheel-də qeydiyyat, söhbət, açıq profil, istifadəçi kontenti, hədəfli reklam, qumar və alış yoxdur. BieMTech-in <strong>12+</strong> tövsiyəsi tapmacaların oxu və düşünmə səviyyəsini göstərir; mağazalar regional reytinqləri ayrıca təyin edə bilər.</p>"],
      ["6. Reklam, analitika və üçüncü tərəflər","<p>Cari versiyada reklam və üçüncü tərəf analitika, izləmə, xəta hesabatı, bulud yaddaşı, sosial şəbəkə və ya alış SDK-sı yoxdur. Google Play Games yeganə istəyə bağlı onlayn inteqrasiyadır və Google siyasətləri ilə idarə olunur. Google Play mağaza və cihaz məlumatlarını oyundan ayrıca emal edə bilər.</p>"],
      ["7. Saxlama, təhlükəsizlik və silmə","<p>Lokal irəliləyiş cihazda silinənədək qalır. Silmək üçün cihaz ayarlarında Word Wheel yaddaşını təmizləyin və ya tətbiqi silin. Cari versiya BieMTech-ə oyun məlumatı göndərmədiyi üçün server silmə sorğusu lazım deyil.</p>"],
      ["8. Dəyişikliklər və əlaqə","<p>Tətbiq və ya məlumat təcrübələri dəyişərsə, siyasəti yeniləyə bilərik. Yeni siyasət aidiyyəti versiyadan əvvəl yayımlanacaq.</p><p>Suallar üçün BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  ru: {
    dir:"ltr", back:"← Политики конфиденциальности BieMTech", subtitle:"Политика конфиденциальности", audience:"Рекомендуется с 12 лет · Игра для широкой аудитории", rights:"Все права защищены.", app:"Приложение", statusLabel:"Статус", status:"Доступно в Google Play", updated:"Последнее обновление", date:"9 сентября 2026 г.",
    summary:"<strong>Кратко:</strong> Word Wheel хранит основной прогресс и настройки на устройстве и не продаёт персональные данные. Основная игра работает офлайн. Необязательные вход в Google Play Games и рейтинг XP используют сервис Google только по вашему выбору. В игре нет рекламы, аналитики и покупок.",
    future:"<strong>До любых изменений:</strong> Если будущая версия добавит онлайн-сервисы, отправку слов, рекламу, аналитику или иной сторонний сервис, эта политика и декларации магазина будут обновлены до выпуска такой функции.",
    sections:[
      ["1. О Word Wheel","<p>Word Wheel — многоязычная словесная головоломка. Игрок соединяет буквы, заполняет кроссворды, находит бонусные слова, получает инструменты, открывает жеоды и коллекционные фоновые карты.</p><p>BieMTech рекомендует игру <strong>с 12 лет</strong>, поскольку загадки требуют чтения, логики и словарного запаса. Игра предназначена для широкой аудитории, а не только для детей.</p>"],
      ["2. Персональные данные и Google Play Games","<p>Word Wheel не запрашивает и не собирает имя, электронную почту, телефон, местоположение, контакты, фотографии, медиа или платёжные данные.</p><p>Если вы выберете вход или рейтинг XP Google Play Games, Google может обрабатывать аккаунт Play Games, идентификатор игрока, профиль и очки по своей политике. Игра отправляет XP и читает рейтинг только для этой необязательной функции.</p>"],
      ["3. Данные только на устройстве","<p>Локальный файл хранит:</p><ul><li>выбранный язык и прогресс по каждому языку;</li><li>монеты, бонусные слова, подсказки, инструменты и прогресс наград;</li><li>открытые фоновые карты, выбранный фон и уровни получения карт;</li><li>настройку звука и версию контент-пакета.</li></ul><p>Эти данные не покидают устройство и недоступны BieMTech.</p>"],
      ["4. Офлайн-работа, подключение и разрешения","<p>Основная игра работает офлайн. Интернет используется только для необязательных входа Google Play Games и рейтинга XP. Игра не запрашивает местоположение, камеру, микрофон, контакты, фотографии, внешнее хранилище или другие чувствительные данные.</p>"],
      ["5. Возраст и дети","<p>В Word Wheel нет регистрации, чата, публичного профиля, пользовательского контента, целевой рекламы, азартных игр или покупок. Рекомендация <strong>12+</strong> отражает уровень чтения и мышления; магазины могут отдельно назначать региональные рейтинги.</p>"],
      ["6. Реклама, аналитика и третьи стороны","<p>В текущей версии нет рекламы и сторонних SDK для аналитики, отслеживания, отчётов об ошибках, облачных сохранений, социальных сетей или покупок. Google Play Games — единственная необязательная онлайн-интеграция, регулируемая политиками Google.</p>"],
      ["7. Хранение и удаление","<p>Локальный прогресс хранится до удаления на устройстве. Очистите данные Word Wheel в настройках или удалите приложение. Серверный запрос не нужен, поскольку текущая версия не отправляет игровые данные BieMTech.</p>"],
      ["8. Изменения и контакт","<p>Политика может обновляться при изменении приложения или работы с данными. Новая версия будет опубликована до соответствующего выпуска.</p><p>Вопросы можно направить BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  tr: {
    dir:"ltr", back:"← BieMTech Gizlilik Politikaları", subtitle:"Gizlilik Politikası", audience:"12 yaş ve üzeri için önerilir · Genel kitle oyunu", rights:"Tüm hakları saklıdır.", app:"Uygulama", statusLabel:"Durum", status:"Google Play'de yayında", updated:"Son güncelleme", date:"9 Eylül 2026",
    summary:"<strong>Kısaca:</strong> Word Wheel temel ilerleme ve tercihleri cihazda tutar ve kişisel verileri satmaz. Ana oyun çevrimdışı çalışır. İsteğe bağlı Google Play Games girişi ve XP liderlik tablosu yalnızca bu özellikleri seçtiğinizde Google hizmetini kullanır. Oyunda reklam, analiz veya satın alma yoktur.",
    future:"<strong>Herhangi bir değişiklikten önce:</strong> Gelecekte çevrimiçi hizmet, kelime raporlama, reklam, analiz veya başka bir üçüncü taraf hizmeti eklenirse bu politika ve mağaza beyanları özellik yayınlanmadan önce güncellenecektir.",
    sections:[
      ["1. Word Wheel hakkında","<p>Word Wheel çok dilli bir kelime bulmacasıdır. Oyuncular harfleri birleştirir, bulmaca tahtalarını doldurur, bonus kelimeler bulur, araçlar kazanır, jeotları açar ve koleksiyonluk arka plan kartları toplar.</p><p>Bulmacalar okuma, düşünme ve kelime bilgisi gerektirdiği için BieMTech oyunu <strong>12 yaş ve üzeri</strong> için önerir. Oyun genel kitleye yöneliktir ve yalnızca çocuklar için tasarlanmamıştır.</p>"],
      ["2. Kişisel veriler ve Google Play Games","<p>Word Wheel ad, e-posta, telefon, konum, kişiler, fotoğraflar, medya veya ödeme bilgilerini <strong>istemez ve toplamaz</strong>.</p><p>Google Play Games girişi veya XP liderlik tablosunu seçerseniz Google, kendi politikasına göre Play Games hesabı, oyuncu kimliği, profil ve puan verilerini işleyebilir. Oyun yalnızca bu isteğe bağlı özellik için XP gönderir ve tabloyu okur.</p>"],
      ["3. Yalnızca cihazda saklanan bilgiler","<p>Yerel ilerleme dosyası şunları saklar:</p><ul><li>seçilen dil ve dil başına seviye ilerlemesi;</li><li>paralar, bonus kelimeler, ipuçları, araçlar ve ödül ilerlemesi;</li><li>açılan arka plan kartları, seçili arka plan ve kartların kazanıldığı seviyeler;</li><li>ses tercihi ve içerik paketi sürümü.</li></ul><p>Bu bilgiler cihazda kalır ve BieMTech tarafından erişilemez.</p>"],
      ["4. Çevrimdışı kullanım, bağlantı ve izinler","<p>Ana oyun çevrimdışı çalışır. İnternet yalnızca isteğe bağlı Google Play Games girişi ve XP liderlik tablosu için kullanılır. Oyun konum, kamera, mikrofon, kişiler, fotoğraflar, harici depolama veya diğer hassas verilere erişim istemez.</p>"],
      ["5. Yaş rehberi ve çocuklar","<p>Word Wheel'de kayıt, sohbet, herkese açık profil, kullanıcı içeriği, hedefli reklam, kumar veya satın alma yoktur. <strong>12+</strong> önerisi bulmacaların okuma ve düşünme seviyesini belirtir; mağazalar bölgesel dereceleri ayrıca verebilir.</p>"],
      ["6. Reklam, analiz ve üçüncü taraflar","<p>Mevcut sürümde reklam ya da analiz, takip, hata raporu, bulut kaydı, sosyal ağ veya satın alma için üçüncü taraf SDK yoktur. Google Play Games tek isteğe bağlı çevrimiçi entegrasyondur ve Google politikalarına tabidir.</p>"],
      ["7. Saklama ve silme","<p>Yerel ilerleme cihazdan silinene kadar kalır. Cihaz ayarlarında Word Wheel depolamasını temizleyin veya uygulamayı kaldırın. Mevcut sürüm BieMTech'e oyun verisi göndermediği için sunucu silme isteği gerekmez.</p>"],
      ["8. Değişiklikler ve iletişim","<p>Uygulama veya veri uygulamaları değişirse politika güncellenebilir. Yeni politika ilgili sürümden önce yayınlanır.</p><p>Sorular için BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  de: {
    dir:"ltr", back:"← BieMTech-Datenschutzrichtlinien", subtitle:"Datenschutzrichtlinie", audience:"Empfohlen ab 12 Jahren · Spiel für ein allgemeines Publikum", rights:"Alle Rechte vorbehalten.", app:"App", statusLabel:"Status", status:"Bei Google Play verfügbar", updated:"Zuletzt aktualisiert", date:"9. September 2026",
    summary:"<strong>Kurz gesagt:</strong> Word Wheel speichert Hauptfortschritt und Einstellungen auf dem Gerät und verkauft keine personenbezogenen Daten. Das Hauptspiel funktioniert offline. Optionale Anmeldung und XP-Bestenliste von Google Play Games nutzen Googles Dienst nur nach Ihrer Wahl. Es gibt keine Werbung, Analysen oder Käufe.",
    future:"<strong>Vor jeder Änderung:</strong> Falls eine künftige Version Onlinedienste, Wortmeldungen, Werbung, Analysen oder andere Drittanbieterdienste hinzufügt, werden diese Richtlinie und die Store-Angaben vor Veröffentlichung aktualisiert.",
    sections:[
      ["1. Über Word Wheel","<p>Word Wheel ist ein mehrsprachiges Worträtsel. Spielende verbinden Buchstaben, füllen Kreuzworträtsel, finden Bonuswörter, verdienen Werkzeuge, öffnen Geoden und sammeln Hintergrundkarten.</p><p>Da die Rätsel Lesen, Denken und Wortschatz erfordern, empfiehlt BieMTech das Spiel <strong>ab 12 Jahren</strong>. Es richtet sich an ein allgemeines Publikum und nicht nur an Kinder.</p>"],
      ["2. Personenbezogene Daten und Google Play Games","<p>Word Wheel fragt nicht nach Name, E-Mail, Telefon, Standort, Kontakten, Fotos, Medien oder Zahlungsdaten und erfasst diese nicht.</p><p>Wenn Sie Anmeldung oder XP-Bestenliste von Google Play Games wählen, kann Google Play-Games-Konto, Spieler-ID, Profil und Punkte nach eigener Richtlinie verarbeiten. Das Spiel sendet XP und liest Einträge nur für diese optionale Funktion.</p>"],
      ["3. Nur auf dem Gerät gespeicherte Daten","<p>Eine lokale Fortschrittsdatei speichert:</p><ul><li>Sprache und Fortschritt je Sprachpaket;</li><li>Münzen, Bonuswörter, Hinweise, Werkzeuge und Belohnungsfortschritt;</li><li>freigeschaltete Karten, ausgewählten Hintergrund und Karten-Level;</li><li>Soundeinstellung und Content-Pack-Version.</li></ul><p>Diese Daten bleiben auf dem Gerät und sind BieMTech nicht zugänglich.</p>"],
      ["4. Offline-Nutzung, Verbindung und Berechtigungen","<p>Das Hauptspiel funktioniert offline. Internet wird nur für optionale Google-Play-Games-Anmeldung und XP-Bestenliste verwendet. Standort, Kamera, Mikrofon, Kontakte, Fotos, externer Speicher oder andere sensible Daten werden nicht angefordert.</p>"],
      ["5. Altersempfehlung und Kinder","<p>Word Wheel enthält keine Registrierung, Chats, öffentlichen Profile, Nutzerinhalte, zielgerichtete Werbung, Glücksspiele oder Käufe. Die Empfehlung <strong>12+</strong> bezieht sich auf Lese- und Denkniveau; Stores können regionale Altersfreigaben separat vergeben.</p>"],
      ["6. Werbung, Analysen und Dritte","<p>Die aktuelle Version enthält keine Werbung und keine Drittanbieter-SDKs für Analysen, Tracking, Fehlerberichte, Cloud-Speicher, soziale Netzwerke oder Käufe. Google Play Games ist die einzige optionale Online-Integration und unterliegt Googles Richtlinien.</p>"],
      ["7. Aufbewahrung und Löschung","<p>Der lokale Fortschritt bleibt bis zur Löschung auf dem Gerät. Löschen Sie die Word-Wheel-App-Daten in den Geräteeinstellungen oder deinstallieren Sie die App. Eine Serveranfrage ist nicht nötig, da keine Spieldaten an BieMTech gesendet werden.</p>"],
      ["8. Änderungen und Kontakt","<p>Wir können diese Richtlinie bei Änderungen an App oder Datenpraxis aktualisieren. Die neue Fassung erscheint vor der betroffenen Version.</p><p>Fragen an BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  fr: {
    dir:"ltr", back:"← Politiques de confidentialité BieMTech", subtitle:"Politique de confidentialité", audience:"Recommandé dès 12 ans · Jeu tout public", rights:"Tous droits réservés.", app:"Application", statusLabel:"Statut", status:"Disponible sur Google Play", updated:"Dernière mise à jour", date:"9 septembre 2026",
    summary:"<strong>En bref :</strong> Word Wheel conserve progression et préférences principales sur l'appareil et ne vend aucune donnée personnelle. Le jeu principal fonctionne hors ligne. La connexion et le classement XP facultatifs de Google Play Games utilisent le service de Google uniquement si vous les choisissez. Il n'y a ni publicité, ni analyse, ni achat.",
    future:"<strong>Avant tout changement :</strong> Si une future version ajoute des services en ligne, le signalement de mots, de la publicité, des analyses ou un autre service tiers, cette politique et les déclarations du store seront mises à jour avant sa publication.",
    sections:[
      ["1. À propos de Word Wheel","<p>Word Wheel est un jeu de mots multilingue. Les joueurs relient des lettres, remplissent des grilles, trouvent des mots bonus, gagnent des outils, ouvrent des géodes et collectionnent des cartes d'arrière-plan.</p><p>Comme les énigmes demandent lecture, réflexion et vocabulaire, BieMTech recommande le jeu <strong>dès 12 ans</strong>. Il s'adresse au grand public et n'est pas conçu uniquement pour les enfants.</p>"],
      ["2. Données personnelles et Google Play Games","<p>Word Wheel ne demande et ne collecte ni nom, e-mail, téléphone, emplacement, contacts, photos, médias ou paiement.</p><p>Si vous choisissez la connexion ou le classement XP Google Play Games, Google peut traiter compte, identifiant de joueur, profil et score selon sa politique. Le jeu envoie l'XP et lit le classement uniquement pour cette fonction facultative.</p>"],
      ["3. Informations stockées uniquement sur l'appareil","<p>Un fichier local conserve :</p><ul><li>la langue et la progression par langue ;</li><li>les pièces, mots bonus, indices, outils et jauges de récompense ;</li><li>les cartes débloquées, le fond choisi et les niveaux d'obtention ;</li><li>le réglage du son et la version du pack.</li></ul><p>Ces informations restent sur l'appareil et ne sont pas accessibles à BieMTech.</p>"],
      ["4. Utilisation hors ligne, connexion et autorisations","<p>Le jeu principal fonctionne hors ligne. Internet sert uniquement à la connexion et au classement XP facultatifs de Google Play Games. Le jeu ne demande pas la position, caméra, microphone, contacts, photos, stockage externe ou autre donnée sensible.</p>"],
      ["5. Âge et enfants","<p>Word Wheel ne propose ni inscription, chat, profil public, contenu utilisateur, publicité ciblée, jeu d'argent ou achat. La recommandation <strong>12+</strong> reflète le niveau de lecture et de réflexion ; les stores peuvent attribuer leurs propres classifications régionales.</p>"],
      ["6. Publicité, analyses et tiers","<p>La version actuelle ne contient aucune publicité ni SDK tiers d'analyse, suivi, rapport d'erreur, sauvegarde cloud, réseau social ou achat. Google Play Games est la seule intégration en ligne facultative et relève des règles de Google.</p>"],
      ["7. Conservation et suppression","<p>La progression locale reste jusqu'à sa suppression sur l'appareil. Effacez les données de Word Wheel dans les réglages ou désinstallez l'application. Aucune demande serveur n'est nécessaire car aucune donnée de jeu n'est envoyée à BieMTech.</p>"],
      ["8. Modifications et contact","<p>Cette politique peut évoluer si l'application ou ses pratiques changent. La nouvelle version sera publiée avant la sortie concernée.</p><p>Questions pour BieMTech :</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  es: {
    dir:"ltr", back:"← Políticas de privacidad de BieMTech", subtitle:"Política de privacidad", audience:"Recomendado para mayores de 12 · Juego para público general", rights:"Todos los derechos reservados.", app:"Aplicación", statusLabel:"Estado", status:"Disponible en Google Play", updated:"Última actualización", date:"9 de septiembre de 2026",
    summary:"<strong>En resumen:</strong> Word Wheel guarda el progreso y las preferencias principales en el dispositivo y no vende datos personales. El juego principal funciona sin conexión. El inicio de sesión y la clasificación de XP opcionales de Google Play Games usan el servicio de Google solo si eliges esas funciones. No hay anuncios, analíticas ni compras.",
    future:"<strong>Antes de cualquier cambio:</strong> Si una versión futura añade servicios en línea, informes de palabras, publicidad, analíticas u otro servicio externo, esta política y las declaraciones de la tienda se actualizarán antes de publicar la función.",
    sections:[
      ["1. Acerca de Word Wheel","<p>Word Wheel es un puzle de palabras multilingüe. Los jugadores conectan letras, completan crucigramas, encuentran palabras extra, ganan herramientas, abren geodas y coleccionan tarjetas de fondo.</p><p>Como los puzles requieren lectura, razonamiento y vocabulario, BieMTech recomienda el juego para <strong>mayores de 12 años</strong>. Es para público general y no está diseñado solo para niños.</p>"],
      ["2. Datos personales y Google Play Games","<p>Word Wheel no solicita ni recopila nombre, correo, teléfono, ubicación, contactos, fotos, archivos multimedia o datos de pago.</p><p>Si eliges el inicio de sesión o la clasificación de XP de Google Play Games, Google puede tratar cuenta, identificador de jugador, perfil y puntuación según su política. El juego solo envía XP y lee la clasificación para esa función opcional.</p>"],
      ["3. Información almacenada solo en el dispositivo","<p>Un archivo local guarda:</p><ul><li>idioma y progreso por idioma;</li><li>monedas, palabras extra, pistas, herramientas y progreso de premios;</li><li>fondos desbloqueados, fondo seleccionado y niveles donde se obtuvieron;</li><li>preferencia de sonido y versión del paquete.</li></ul><p>Estos datos permanecen en el dispositivo y BieMTech no puede acceder a ellos.</p>"],
      ["4. Uso sin conexión, conectividad y permisos","<p>El juego principal funciona sin conexión. Internet se usa solo para el inicio de sesión y la clasificación de XP opcionales de Google Play Games. El juego no solicita ubicación, cámara, micrófono, contactos, fotos, almacenamiento externo u otros datos sensibles.</p>"],
      ["5. Edad y menores","<p>Word Wheel no incluye registro, chat, perfil público, contenido de usuario, publicidad dirigida, apuestas ni compras. La recomendación <strong>12+</strong> refleja el nivel de lectura y razonamiento; las tiendas pueden asignar clasificaciones regionales por separado.</p>"],
      ["6. Anuncios, analíticas y terceros","<p>La versión actual no contiene anuncios ni SDK de terceros para analíticas, seguimiento, fallos, guardado en la nube, redes sociales o compras. Google Play Games es la única integración online opcional y se rige por las políticas de Google.</p>"],
      ["7. Conservación y eliminación","<p>El progreso local permanece hasta que se elimina del dispositivo. Borra los datos de Word Wheel en los ajustes o desinstala la aplicación. No hace falta una solicitud al servidor porque no se envían datos de juego a BieMTech.</p>"],
      ["8. Cambios y contacto","<p>Podemos actualizar esta política si cambian la aplicación o sus prácticas. La nueva política se publicará antes de la versión afectada.</p><p>Preguntas para BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  pt: {
    dir:"ltr", back:"← Políticas de Privacidade da BieMTech", subtitle:"Política de Privacidade", audience:"Recomendado para maiores de 12 · Jogo para público geral", rights:"Todos os direitos reservados.", app:"Aplicativo", statusLabel:"Status", status:"Disponível no Google Play", updated:"Última atualização", date:"9 de setembro de 2026",
    summary:"<strong>Em resumo:</strong> Word Wheel guarda progresso e preferências principais no aparelho e não vende dados pessoais. O jogo principal funciona offline. O login e o placar de XP opcionais do Google Play Games usam o serviço do Google apenas se você escolher esses recursos. Não há anúncios, análises ou compras.",
    future:"<strong>Antes de qualquer mudança:</strong> Se uma versão futura adicionar serviços online, relato de palavras, publicidade, análises ou outro serviço de terceiros, esta política e as declarações da loja serão atualizadas antes do lançamento.",
    sections:[
      ["1. Sobre o Word Wheel","<p>Word Wheel é um jogo de palavras multilíngue. Os jogadores ligam letras, preenchem palavras cruzadas, encontram palavras bônus, ganham ferramentas, abrem geodos e colecionam cartões de fundo.</p><p>Como os desafios exigem leitura, raciocínio e vocabulário, a BieMTech recomenda o jogo para <strong>maiores de 12 anos</strong>. Ele é para o público geral e não foi criado apenas para crianças.</p>"],
      ["2. Dados pessoais e Google Play Games","<p>Word Wheel não pede nem coleta nome, e-mail, telefone, localização, contatos, fotos, mídia ou pagamento.</p><p>Se você escolher login ou placar de XP do Google Play Games, o Google pode tratar conta, identificador de jogador, perfil e pontuação conforme sua política. O jogo só envia XP e lê o placar para esse recurso opcional.</p>"],
      ["3. Informações armazenadas apenas no aparelho","<p>Um arquivo local guarda:</p><ul><li>idioma e progresso por idioma;</li><li>moedas, palavras bônus, dicas, ferramentas e progresso de recompensas;</li><li>fundos desbloqueados, fundo escolhido e níveis em que foram obtidos;</li><li>preferência de som e versão do pacote.</li></ul><p>Esses dados ficam no aparelho e não são acessíveis à BieMTech.</p>"],
      ["4. Uso offline, conectividade e permissões","<p>O jogo principal funciona offline. A Internet é usada apenas para login e placar de XP opcionais do Google Play Games. O jogo não pede localização, câmera, microfone, contatos, fotos, armazenamento externo ou outros dados sensíveis.</p>"],
      ["5. Idade e crianças","<p>Word Wheel não possui cadastro, chat, perfil público, conteúdo de usuário, publicidade direcionada, apostas ou compras. A recomendação <strong>12+</strong> reflete o nível de leitura e raciocínio; as lojas podem atribuir classificações regionais separadamente.</p>"],
      ["6. Anúncios, análises e terceiros","<p>A versão atual não contém anúncios nem SDK de terceiros para análises, rastreamento, falhas, nuvem, redes sociais ou compras. Google Play Games é a única integração online opcional e segue as políticas do Google.</p>"],
      ["7. Retenção e exclusão","<p>O progresso local permanece até ser apagado no aparelho. Limpe os dados do Word Wheel nas configurações ou desinstale o aplicativo. Não é preciso pedir exclusão ao servidor porque nenhum dado do jogo é enviado à BieMTech.</p>"],
      ["8. Mudanças e contato","<p>Podemos atualizar esta política se o aplicativo ou suas práticas mudarem. A nova política será publicada antes da versão afetada.</p><p>Perguntas para a BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  it: {
    dir:"ltr", back:"← Informative privacy BieMTech", subtitle:"Informativa sulla privacy", audience:"Consigliato dai 12 anni · Gioco per il pubblico generale", rights:"Tutti i diritti riservati.", app:"App", statusLabel:"Stato", status:"Disponibile su Google Play", updated:"Ultimo aggiornamento", date:"9 settembre 2026",
    summary:"<strong>In breve:</strong> Word Wheel conserva progressi e preferenze principali sul dispositivo e non vende dati personali. Il gioco principale funziona offline. Accesso e classifica XP facoltativi di Google Play Games usano il servizio Google solo se scelti. Non ci sono annunci, analisi o acquisti.",
    future:"<strong>Prima di ogni modifica:</strong> Se una versione futura aggiungerà servizi online, segnalazione di parole, pubblicità, analisi o altri servizi di terze parti, questa informativa e le dichiarazioni dello store saranno aggiornate prima del rilascio.",
    sections:[
      ["1. Informazioni su Word Wheel","<p>Word Wheel è un rompicapo di parole multilingue. I giocatori collegano lettere, completano schemi, trovano parole bonus, ottengono strumenti, aprono geodi e collezionano carte sfondo.</p><p>Poiché i rompicapi richiedono lettura, ragionamento e vocabolario, BieMTech consiglia il gioco <strong>dai 12 anni</strong>. È rivolto al pubblico generale e non solo ai bambini.</p>"],
      ["2. Dati personali e Google Play Games","<p>Word Wheel non richiede né raccoglie nome, e-mail, telefono, posizione, contatti, foto, media o pagamenti.</p><p>Se scegli accesso o classifica XP di Google Play Games, Google può trattare account, ID giocatore, profilo e punteggio secondo la propria politica. Il gioco invia XP e legge la classifica solo per questa funzione facoltativa.</p>"],
      ["3. Informazioni conservate solo sul dispositivo","<p>Un file locale salva:</p><ul><li>lingua e avanzamento per lingua;</li><li>monete, parole bonus, suggerimenti, strumenti e premi;</li><li>sfondi sbloccati, sfondo scelto e livelli di ottenimento;</li><li>preferenza audio e versione del pacchetto.</li></ul><p>Questi dati restano sul dispositivo e non sono accessibili a BieMTech.</p>"],
      ["4. Uso offline, connettività e autorizzazioni","<p>Il gioco principale funziona offline. Internet serve solo per accesso e classifica XP facoltativi di Google Play Games. Il gioco non richiede posizione, fotocamera, microfono, contatti, foto, memoria esterna o altri dati sensibili.</p>"],
      ["5. Età e minori","<p>Word Wheel non include registrazione, chat, profili pubblici, contenuti utente, pubblicità mirata, gioco d'azzardo o acquisti. La raccomandazione <strong>12+</strong> riflette il livello di lettura e ragionamento; gli store possono assegnare valutazioni regionali separate.</p>"],
      ["6. Annunci, analisi e terze parti","<p>La versione attuale non contiene annunci né SDK di terze parti per analisi, tracciamento, crash, cloud, social network o acquisti. Google Play Games è l'unica integrazione online facoltativa ed è regolata dalle politiche Google.</p>"],
      ["7. Conservazione ed eliminazione","<p>I progressi locali restano finché non vengono eliminati dal dispositivo. Cancella i dati di Word Wheel nelle impostazioni o disinstalla l'app. Non serve una richiesta al server perché nessun dato di gioco viene inviato a BieMTech.</p>"],
      ["8. Modifiche e contatti","<p>Possiamo aggiornare l'informativa se cambiano l'app o le sue pratiche. La nuova versione sarà pubblicata prima del rilascio interessato.</p><p>Domande a BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  ar: {
    dir:"rtl", back:"سياسات خصوصية BieMTech ←", subtitle:"سياسة الخصوصية", audience:"موصى به لعمر 12+ · لعبة للجمهور العام", rights:"جميع الحقوق محفوظة.", app:"التطبيق", statusLabel:"الحالة", status:"متاحة على Google Play", updated:"آخر تحديث", date:"9 سبتمبر 2026",
    summary:"<strong>باختصار:</strong> تحفظ Word Wheel التقدم والتفضيلات الأساسية على الجهاز ولا تبيع البيانات الشخصية. تعمل اللعبة الأساسية دون اتصال. يستخدم تسجيل الدخول ولوحة صدارة XP الاختياريان في Google Play Games خدمة Google فقط عند اختيارهما. لا توجد إعلانات أو تحليلات أو مشتريات.",
    future:"<strong>قبل أي تغيير:</strong> إذا أضاف إصدار مستقبلي خدمات عبر الإنترنت أو إرسال الكلمات أو الإعلانات أو التحليلات أو خدمة خارجية أخرى، فسيتم تحديث هذه السياسة وإفصاحات المتجر قبل إصدار الميزة.",
    sections:[
      ["1. حول Word Wheel","<p>Word Wheel لعبة ألغاز كلمات متعددة اللغات. يصل اللاعبون الحروف ويملؤون لوحات الكلمات ويجدون كلمات إضافية ويكسبون أدوات ويفتحون الجيود ويجمعون بطاقات الخلفيات.</p><p>لأن الألغاز تتطلب القراءة والتفكير والمعرفة اللغوية، توصي BieMTech باللعبة <strong>لعمر 12 سنة فأكثر</strong>. وهي موجهة للجمهور العام وليست للأطفال فقط.</p>"],
      ["2. البيانات الشخصية وGoogle Play Games","<p>لا تطلب Word Wheel أو تجمع الاسم أو البريد أو الهاتف أو الموقع أو جهات الاتصال أو الصور أو الوسائط أو الدفع.</p><p>إذا اخترت تسجيل الدخول أو لوحة XP، فقد تعالج Google حساب Play Games ومعرف اللاعب والملف والنتيجة وفق سياستها. ترسل اللعبة XP وتقرأ اللوحة لهذه الميزة الاختيارية فقط.</p>"],
      ["3. معلومات محفوظة على الجهاز فقط","<p>يحفظ ملف محلي:</p><ul><li>اللغة والتقدم لكل لغة؛</li><li>العملات والكلمات الإضافية والتلميحات والأدوات والمكافآت؛</li><li>الخلفيات المفتوحة والخلفية المختارة ومستويات الحصول عليها؛</li><li>تفضيل الصوت وإصدار حزمة المحتوى.</li></ul><p>تبقى هذه البيانات على الجهاز ولا تستطيع BieMTech الوصول إليها.</p>"],
      ["4. اللعب دون اتصال والاتصال والأذونات","<p>تعمل اللعبة الأساسية دون اتصال. يستخدم الإنترنت فقط لتسجيل Google Play Games ولوحة XP الاختياريين. لا تطلب اللعبة الموقع أو الكاميرا أو الميكروفون أو جهات الاتصال أو الصور أو التخزين الخارجي أو بيانات حساسة أخرى.</p>"],
      ["5. العمر والأطفال","<p>لا تحتوي Word Wheel على تسجيل أو دردشة أو ملف عام أو محتوى مستخدم أو إعلان موجّه أو مقامرة أو شراء. تعكس توصية <strong>12+</strong> مستوى القراءة والتفكير، وقد تعيّن المتاجر تصنيفات إقليمية بشكل منفصل.</p>"],
      ["6. الإعلانات والتحليلات والجهات الخارجية","<p>لا يحتوي الإصدار الحالي على إعلانات أو SDK خارجي للتحليلات أو التتبع أو الأعطال أو السحابة أو الشبكات الاجتماعية أو الشراء. Google Play Games هو التكامل الاختياري الوحيد عبر الإنترنت ويخضع لسياسات Google.</p>"],
      ["7. الاحتفاظ والحذف","<p>يبقى التقدم المحلي حتى حذفه من الجهاز. امسح بيانات Word Wheel من الإعدادات أو أزل التطبيق. لا يلزم طلب حذف من خادم لأن الإصدار الحالي لا يرسل بيانات اللعب إلى BieMTech.</p>"],
      ["8. التغييرات والتواصل","<p>قد نحدّث السياسة عند تغير التطبيق أو ممارساته. ستنشر السياسة الجديدة قبل الإصدار المتأثر.</p><p>للاستفسار تواصل مع BieMTech:</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  zh: {
    dir:"ltr", back:"← BieMTech 隐私政策", subtitle:"隐私政策", audience:"建议12岁以上 · 面向普通用户", rights:"保留所有权利。", app:"应用", statusLabel:"状态", status:"已在 Google Play 上线", updated:"最后更新", date:"2026年9月9日",
    summary:"<strong>简而言之：</strong>Word Wheel 将核心进度和偏好保存在设备上，不出售个人数据。核心游戏可离线游玩。只有当您选择可选的 Google Play Games 登录和 XP 排行榜时才会使用 Google 服务。游戏没有广告、分析或购买。",
    future:"<strong>任何变化之前：</strong>如果未来版本加入在线服务、单词报告、广告、分析或其他第三方服务，我们会在该功能发布前更新本政策和相关商店披露。",
    sections:[
      ["1. 关于 Word Wheel","<p>Word Wheel 是一款多语言文字谜题。玩家连接字母、填写纵横字谜、寻找奖励词、获得工具、打开晶洞并收藏背景卡。</p><p>由于谜题需要阅读、推理和词汇知识，BieMTech 建议 <strong>12岁以上</strong>游玩。本游戏面向普通用户，并非仅为儿童设计。</p>"],
      ["2. 个人数据与 Google Play Games","<p>Word Wheel 本身不会要求或收集姓名、邮箱、电话、位置、联系人、照片、媒体或付款信息。</p><p>如果选择 Google Play Games 登录或 XP 排行榜，Google 可按其政策处理 Play Games 账户、玩家标识、资料和分数。游戏仅为此可选功能提交 XP 并读取排行榜。</p>"],
      ["3. 仅存储在设备上的信息","<p>本地进度文件保存：</p><ul><li>所选语言及各语言进度；</li><li>金币、奖励词、提示、工具和奖励进度；</li><li>已解锁背景、当前背景和获得卡片的关卡；</li><li>声音偏好和内容包版本。</li></ul><p>这些信息保留在设备上，BieMTech 无法访问。</p>"],
      ["4. 离线使用、联网与权限","<p>核心游戏可离线游玩。互联网仅用于可选的 Google Play Games 登录和 XP 排行榜。游戏不要求位置、相机、麦克风、联系人、照片、外部存储或其他敏感数据。</p>"],
      ["5. 年龄指导与儿童","<p>Word Wheel 没有注册、聊天、公开资料、用户内容、定向广告、赌博或购买。<strong>12+</strong>建议反映谜题的阅读和推理水平；应用商店可另行给出地区评级。</p>"],
      ["6. 广告、分析和第三方","<p>当前版本没有广告，也没有用于分析、跟踪、崩溃报告、云存档、社交网络或购买的第三方 SDK。Google Play Games 是唯一可选在线集成，并受 Google 政策约束。</p>"],
      ["7. 保留与删除","<p>本地进度会保留至从设备删除。在设置中清除 Word Wheel 数据或卸载应用即可删除。当前版本不会向 BieMTech 发送游戏数据，因此无需服务器删除请求。</p>"],
      ["8. 变更与联系","<p>应用或数据做法发生变化时，我们可能更新本政策。新政策将在受影响版本之前发布。</p><p>问题请联系 BieMTech：</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  },
  ja: {
    dir:"ltr", back:"← BieMTech プライバシーポリシー", subtitle:"プライバシーポリシー", audience:"12歳以上推奨 · 一般向けゲーム", rights:"無断転載を禁じます。", app:"アプリ", statusLabel:"状態", status:"Google Play で配信中", updated:"最終更新", date:"2026年9月9日",
    summary:"<strong>要約：</strong>Word Wheel は基本の進行状況と設定を端末内に保存し、個人データを販売しません。基本ゲームはオフラインで遊べます。任意の Google Play Games ログインとXPランキングは選択時のみGoogleのサービスを利用します。広告、解析、購入はありません。",
    future:"<strong>変更前のお知らせ：</strong>将来オンラインサービス、単語報告、広告、解析、その他の第三者サービスを追加する場合、このポリシーとストアの開示を機能公開前に更新します。",
    sections:[
      ["1. Word Wheel について","<p>Word Wheel は多言語ワードパズルです。文字をつなぎ、クロスワード盤を埋め、ボーナスワードを見つけ、道具を獲得し、ジオードや背景カードを開きます。</p><p>パズルには読解、推理、語彙力が必要なため、BieMTech は<strong>12歳以上</strong>を推奨しています。一般向けのゲームで、子ども専用ではありません。</p>"],
      ["2. 個人データと Google Play Games","<p>Word Wheel 自体は氏名、メール、電話、位置情報、連絡先、写真、メディア、支払い情報を求めたり収集したりしません。</p><p>Google Play Games ログインまたはXPランキングを選ぶと、Googleは自社ポリシーに従ってアカウント、プレイヤーID、プロフィール、スコアを処理する場合があります。ゲームはこの任意機能のためだけにXPを送信しランキングを読みます。</p>"],
      ["3. 端末内だけに保存される情報","<p>ローカル進行ファイルには次を保存します。</p><ul><li>選択言語と言語ごとの進行状況</li><li>コイン、ボーナスワード、ヒント、道具、報酬の進行</li><li>開放した背景、選択中の背景、カード獲得レベル</li><li>サウンド設定とコンテンツパック版</li></ul><p>これらは端末内に留まり、BieMTech はアクセスできません。</p>"],
      ["4. オフライン利用、通信、権限","<p>基本ゲームはオフラインで遊べます。インターネットは任意の Google Play Games ログインとXPランキングにのみ使用します。位置情報、カメラ、マイク、連絡先、写真、外部ストレージなどの機微データは要求しません。</p>"],
      ["5. 年齢案内と子ども","<p>Word Wheel には登録、チャット、公開プロフィール、ユーザー投稿、ターゲット広告、ギャンブル、購入がありません。<strong>12+</strong>推奨は読解・推理レベルを示し、ストアは地域別レーティングを別途設定できます。</p>"],
      ["6. 広告、解析、第三者","<p>現在のバージョンには広告や、解析、追跡、クラッシュ報告、クラウド保存、SNS、購入用の第三者SDKはありません。Google Play Games が唯一の任意オンライン連携で、Googleのポリシーが適用されます。</p>"],
      ["7. 保持と削除","<p>ローカル進行状況は端末で削除されるまで残ります。設定で Word Wheel のデータを消去するか、アプリをアンインストールしてください。現在の版はゲームデータを BieMTech に送らないため、サーバー削除依頼は不要です。</p>"],
      ["8. 変更と連絡先","<p>アプリやデータ取扱いが変わる場合、本ポリシーを更新することがあります。改訂版は対象リリース前に公開します。</p><p>BieMTech へのお問い合わせ：</p><a class=\"contact-link\" href=\"mailto:info@biemtech.com\">info@biemtech.com</a>"]
    ]
  }
};
